	tilepal 0, ROOF, BROWN, BROWN, RED, GREEN, GREEN, ROOF, GRAY
	tilepal 0, RED, RED, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, GREEN, WATER, GREEN, BROWN, BROWN
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, ROOF, GREEN, GREEN
	tilepal 0, ROOF, ROOF, ROOF, RED, RED, GRAY, YELLOW, BROWN
	tilepal 0, BROWN, GREEN, GREEN, BROWN, BROWN, BROWN, ROOF, ROOF
	tilepal 0, ROOF, BROWN, BROWN, BROWN, BROWN, GRAY, ROOF, YELLOW
	tilepal 0, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, BROWN, ROOF, ROOF, BROWN, BROWN, BROWN, ROOF
	tilepal 0, ROOF, WATER, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, BROWN, BROWN, ROOF, BROWN, ROOF, ROOF, ROOF
	tilepal 0, WATER, GRAY, GRAY, ROOF, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, RED, GREEN, GRAY, WATER, BROWN, GRAY
	tilepal 1, GRAY, GRAY, GRAY, YELLOW, YELLOW, GRAY, GRAY, GRAY
	tilepal 1, GREEN, GRAY, GRAY, GREEN, RED, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GREEN, GRAY, GRAY, ROOF, GRAY, GRAY
	tilepal 1, GRAY, WATER, GRAY, WATER, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
