	tilepal 0, WATER, RED, RED, RED, RED, BROWN, WATER, WATER
	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, WATER, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, RED, RED, BROWN, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, GREEN, WATER, WATER, WATER, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, WATER, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, WATER, WATER, BROWN, BROWN
	tilepal 0, GRAY, GRAY, WATER, GRAY, BROWN, BROWN, BROWN, WATER
	tilepal 0, RED, RED, BROWN, BROWN, GREEN, YELLOW, BROWN, BROWN
	tilepal 0, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GRAY, BROWN, BROWN, BROWN, RED, RED, WATER, WATER
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, RED, BROWN, WATER, WATER
	tilepal 1, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
