	tilepal 0, GRAY, WATER, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, RED, RED, BROWN, BROWN
	tilepal 0, ROOF, ROOF, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF, BROWN, BROWN
	tilepal 0, ROOF, ROOF, GREEN, WATER, WATER, WATER, RED, RED
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, GREEN, GREEN, RED, RED, GRAY, RED
	tilepal 0, RED, RED, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, GREEN, GREEN, GRAY, BROWN, WATER
	tilepal 0, BROWN, BROWN, GRAY, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, BROWN, ROOF
	tilepal 0, ROOF, ROOF, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GRAY, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GREEN, GREEN, WATER, RED, GRAY, GRAY, ROOF, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, RED, ROOF, ROOF, GRAY, YELLOW
	tilepal 1, GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal 1, WATER, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, RED, RED, RED, RED, WATER, WATER
	tilepal 1, WATER, WATER, RED, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 1, GREEN, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, RED, YELLOW, YELLOW, YELLOW, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, RED, RED, BROWN, BROWN
