	tilepal 0, ROOF, ROOF, GREEN, RED, BROWN, BROWN, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN
	tilepal 0, ROOF, ROOF, ROOF, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GREEN, ROOF, ROOF, ROOF, ROOF, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, GREEN, YELLOW, YELLOW, GREEN, GRAY, ROOF, ROOF
	tilepal 0, BROWN, BROWN, RED, RED, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, GREEN, BROWN, ROOF, ROOF
	tilepal 0, BROWN, BROWN, RED, RED, RED, RED, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, GRAY, BROWN, ROOF, ROOF
	tilepal 0, ROOF, BROWN, RED, RED, YELLOW, YELLOW, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, WATER, BROWN, BROWN, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, GRAY, ROOF, RED, RED, RED, ROOF, ROOF, GREEN
	tilepal 1, GREEN, GRAY, GREEN, GREEN, GREEN, GREEN, WATER, GREEN
	tilepal 1, GRAY, GRAY, WATER, GRAY, RED, ROOF, ROOF, BROWN
	tilepal 1, BROWN, RED, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 1, GRAY, RED, GRAY, GRAY, GRAY, ROOF, GREEN, BROWN
	tilepal 1, RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 1, RED, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, ROOF, ROOF
	tilepal 1, WATER, GREEN, GREEN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, WATER, RED, WATER, WATER, ROOF, ROOF
