	tilepal 0, GRAY, ROOF, RED, RED, RED, ROOF, ROOF, GREEN
	tilepal 0, GREEN, GRAY, GREEN, GREEN, GREEN, GREEN, WATER, WATER
	tilepal 0, GRAY, GRAY, WATER, GRAY, RED, ROOF, ROOF, BROWN
	tilepal 0, BROWN, RED, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 0, GRAY, RED, GRAY, GRAY, GRAY, ROOF, GREEN, BROWN
	tilepal 0, RED, RED, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 0, RED, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, ROOF, ROOF
	tilepal 0, WATER, GREEN, GREEN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, WATER, RED, WATER, WATER, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, GRAY, BROWN, WATER, WATER, RED, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, WATER, WATER, RED, BROWN, GRAY, GRAY
	tilepal 1, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN, RED, GRAY
	tilepal 1, GRAY, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, BROWN
