	tilepal 0, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY
	tilepal 0, GRAY, GREEN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, ROOF, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, WATER, WATER, WATER, WATER
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER
	tilepal 0, WATER, GREEN, GREEN, WATER, BROWN, BROWN, BROWN, GREEN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN, WATER, WATER

rept 16
	db $ff
endr

	tilepal 1, GRAY, RED, RED, GREEN, GREEN, YELLOW, YELLOW, WATER
	tilepal 1, WATER, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, GRAY
	tilepal 1, GRAY, RED, GRAY, GREEN, GRAY, YELLOW, GRAY, WATER
	tilepal 1, GRAY, GRAY, RED, RED, RED, BROWN, BROWN, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 1, RED, RED, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, RED, WATER, WATER, ROOF, GRAY, GRAY
