	tilepal 0, GRAY, RED, RED, GREEN, GREEN, YELLOW, YELLOW, WATER
	tilepal 0, WATER, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, RED, GRAY, GREEN, GRAY, YELLOW, GRAY, WATER
	tilepal 0, GRAY, GRAY, RED, RED, RED, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, BROWN, YELLOW, WATER
	tilepal 0, BROWN, RED, RED, RED, RED, WATER, WATER, WATER
	tilepal 0, WATER, GREEN, GREEN, GREEN, GREEN, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, RED, WATER, WATER, ROOF, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, WATER, WATER, WATER, GRAY, BROWN, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, RED, WATER, GREEN, YELLOW, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GREEN
	tilepal 1, GREEN, BROWN, BROWN, WATER, GREEN, RED, RED, RED
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, WATER, GRAY, GREEN
	tilepal 1, GREEN, BROWN, BROWN, WATER, GREEN, GRAY, GRAY, RED
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY, ROOF
	tilepal 1, BROWN, BROWN, BROWN, BROWN, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, GRAY, GRAY, ROOF
