	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, GRAY, GRAY, WATER, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, WATER, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, RED
	tilepal 1, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 1, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
