	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, BROWN, RED
	tilepal 0, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 1, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, GRAY, ROOF, GRAY, GRAY, WATER, ROOF, ROOF, ROOF
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, BROWN, ROOF, GRAY, GRAY, ROOF, ROOF
	tilepal 1, ROOF, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
