	tilepal 0, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, GRAY, ROOF, GRAY, GRAY, WATER, ROOF, ROOF, ROOF
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 1, YELLOW, YELLOW, ROOF, ROOF, GREEN, GREEN, GREEN, GREEN
	tilepal 1, RED, RED, RED, GRAY, WATER, ROOF, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 1, GRAY, GRAY, GRAY, BROWN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN, GREEN
	tilepal 1, BROWN, RED, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, BROWN, GREEN, GREEN, WATER, WATER, WATER, RED
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, BROWN
	tilepal 1, BROWN, BROWN, GRAY, GRAY, WATER, WATER, WATER, GRAY
