	tilepal 0, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, BROWN, YELLOW, YELLOW, BROWN, BROWN
	tilepal 0, BROWN, RED, BROWN, BROWN, RED, GREEN, GREEN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, GREEN, GREEN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, RED, RED, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, RED
	tilepal 0, RED, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, BROWN, RED, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 1, WATER, RED, WATER, WATER, GRAY, GRAY, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, BROWN, BROWN
	tilepal 1, WATER, RED, RED, RED, RED, WATER, GRAY, GRAY
	tilepal 1, WATER, WATER, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, WATER, RED, RED, RED, RED, WATER, GRAY, GRAY
	tilepal 1, GRAY, GRAY, BROWN, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, RED, BROWN, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 1, WATER, WATER, WATER, RED, RED, RED, RED, WATER
	tilepal 1, BROWN, YELLOW, RED, BROWN, BROWN, BROWN, RED, RED
	tilepal 1, WATER, RED, RED, RED, RED, GRAY, RED, WATER
