	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 0, RED, GREEN, GREEN, GREEN, GREEN, WATER, WATER, WATER
	tilepal 0, WATER, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN
	tilepal 0, BROWN, ROOF, ROOF, ROOF, ROOF, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, BROWN, BROWN, RED
	tilepal 0, GREEN, GREEN, GRAY, RED, RED, RED, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN
	tilepal 0, WATER, GREEN, BROWN, BROWN, RED, RED, BROWN, BROWN
	tilepal 0, BROWN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN, RED
	tilepal 0, RED, BROWN, YELLOW, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN, WATER, WATER
	tilepal 0, BROWN, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, GRAY, YELLOW, YELLOW, YELLOW, YELLOW, ROOF
	tilepal 1, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, GRAY, ROOF
	tilepal 1, ROOF, ROOF, ROOF, YELLOW, YELLOW, YELLOW, YELLOW, ROOF
	tilepal 1, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF
	tilepal 1, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, ROOF, ROOF
	tilepal 1, ROOF, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, RED, RED, GREEN, GREEN, WATER, WATER, YELLOW, YELLOW
	tilepal 1, BROWN, BROWN, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, GRAY, WATER, WATER, RED, RED, GRAY, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
