	tilepal 0, GRAY, ROOF, ROOF, RED, BROWN, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, YELLOW, YELLOW, YELLOW, GRAY, BROWN, GRAY
	tilepal 0, GRAY, ROOF, ROOF, ROOF, WATER, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GRAY, BROWN, BROWN, GRAY, ROOF, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, GRAY, GRAY, GREEN, GREEN, GREEN, GRAY
	tilepal 0, BROWN, BROWN, GRAY, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN, GRAY
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 0, ROOF, ROOF, GRAY, BROWN, GRAY, GRAY, GRAY, RED
	tilepal 0, GREEN, GREEN, GREEN, ROOF, BROWN, BROWN, BROWN, BROWN
	tilepal 0, ROOF, ROOF, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, RED, RED, RED, GRAY, GRAY, RED, RED
	tilepal 1, GREEN, GREEN, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW
	tilepal 1, ROOF, ROOF, RED, RED, GRAY, GRAY, RED, RED
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, YELLOW, YELLOW
	tilepal 1, BROWN, BROWN, WATER, WATER, GREEN, GREEN, YELLOW, YELLOW
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, YELLOW, YELLOW
	tilepal 1, BROWN, BROWN, WATER, WATER, GREEN, GREEN, YELLOW, YELLOW
	tilepal 1, GRAY, GRAY, GRAY, GRAY, WATER, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, RED, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
