	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW
	tilepal 0, RED, RED, RED, RED, GRAY, GRAY, RED, RED
	tilepal 0, GRAY, GRAY, YELLOW, YELLOW, GREEN, GREEN, YELLOW, YELLOW
	tilepal 0, RED, RED, RED, RED, GRAY, GRAY, RED, RED
	tilepal 0, RED, RED, RED, RED, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, WATER, WATER, GREEN, GREEN, GRAY, GRAY
	tilepal 0, RED, RED, RED, RED, BROWN, BROWN, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, WATER, WATER, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, WATER, RED, RED, RED
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, RED, RED, RED
	tilepal 0, RED, RED, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED
	tilepal 1, RED, RED, RED, GREEN, GREEN, WATER, WATER, YELLOW
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, RED, RED, RED
	tilepal 1, RED, RED, RED, GREEN, GREEN, WATER, WATER, YELLOW
