	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY
	tilepal 0, BROWN, YELLOW, YELLOW, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, YELLOW, YELLOW, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GRAY, GRAY
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, WATER, WATER, WATER, GRAY, GRAY, GRAY
	tilepal 0, RED, RED, RED, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 1, GREEN, GREEN, GREEN, GRAY, GREEN, GREEN, GREEN, WATER
	tilepal 1, GREEN, GREEN, GRAY, GRAY, WATER, GRAY, GRAY, GRAY
	tilepal 1, ROOF, GRAY, GRAY, GRAY, GRAY, BROWN, ROOF, RED
	tilepal 1, GRAY, GRAY, RED, GREEN, GRAY, GRAY, ROOF, GRAY
	tilepal 1, GRAY, RED, GRAY, RED, GRAY, GREEN, ROOF, ROOF
	tilepal 1, GRAY, ROOF, WATER, GRAY, GRAY, BROWN, ROOF, GRAY
	tilepal 1, GRAY, GRAY, ROOF, BROWN, BROWN, RED, GREEN, GREEN
	tilepal 1, GRAY, GRAY, RED, RED, ROOF, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, GREEN, WATER, GREEN
	tilepal 1, BROWN, BROWN, RED, RED, BROWN, BROWN, BROWN, ROOF
	tilepal 1, GREEN, GREEN, ROOF, ROOF, ROOF, RED, RED, GRAY
