	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, RED, YELLOW, GREEN, WATER
	tilepal 0, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 0, YELLOW, WATER, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, WATER, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, WATER, YELLOW, YELLOW, YELLOW, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, RED, YELLOW, GREEN, WATER, RED, RED, RED, RED
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GREEN, GREEN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, RED, RED, GRAY, WATER, GRAY, ROOF
	tilepal 1, GRAY, GRAY, YELLOW, GRAY, GRAY, GRAY, GRAY, YELLOW
	tilepal 1, WATER, RED, WATER, RED, WATER, RED, WATER, RED
	tilepal 1, WATER, RED, WATER, RED, WATER, RED, WATER, RED
	tilepal 1, GRAY, GRAY, GREEN, GRAY, GRAY, GREEN, GRAY, ROOF
	tilepal 1, RED, GREEN, GRAY, GREEN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, YELLOW, GRAY, GRAY, RED, GRAY, GRAY, WATER, RED
	tilepal 1, WATER, GREEN, GRAY, GRAY, GREEN, GRAY, GRAY, WATER
	tilepal 1, GRAY, ROOF, GRAY, GRAY, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, BROWN, YELLOW, YELLOW, RED, RED, RED
	tilepal 1, YELLOW, YELLOW, YELLOW, YELLOW, BROWN, BROWN, BROWN, BROWN
	tilepal 1, YELLOW, YELLOW, GRAY, GRAY, YELLOW, YELLOW, GRAY, YELLOW
