	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW
	tilepal 0, YELLOW, RED, RED, RED, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 0, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, GRAY, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, BROWN, YELLOW, YELLOW, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, GRAY, GRAY
	tilepal 0, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW, YELLOW
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY

rept 16
	db $ff
endr

	tilepal 1, GREEN, GRAY, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 1, RED, BROWN, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 1, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, RED, RED, WATER, WATER, GREEN, GREEN
	tilepal 1, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 1, BROWN, BROWN, RED, RED, WATER, WATER, GREEN, GREEN
