	tilepal 0, GREEN, GRAY, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 0, RED, BROWN, GRAY, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, WATER, WATER, YELLOW, YELLOW, GRAY, GRAY, GRAY, GRAY
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN, GREEN
	tilepal 0, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, RED, WATER, WATER, GREEN, GREEN
	tilepal 0, RED, RED, RED, RED, BROWN, BROWN, BROWN, BROWN
	tilepal 0, BROWN, BROWN, RED, RED, WATER, WATER, GREEN, GREEN

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 1, WATER, WATER, WATER, WATER, WATER, WATER, WATER, WATER
