	tilepal 0, BROWN, BROWN, BROWN, WATER, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GREEN, GRAY, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, WATER, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, GRAY, GRAY
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN
	tilepal 0, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GREEN, GREEN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 1, GRAY, GREEN, GREEN, GREEN, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
