	tilepal 0, GRAY, WATER, WATER, WATER, WATER, RED, RED, RED
	tilepal 0, RED, RED, WATER, WATER, YELLOW, YELLOW, RED, RED
	tilepal 0, RED, WATER, WATER, WATER, WATER, RED, RED, RED
	tilepal 0, RED, RED, WATER, WATER, GRAY, GRAY, RED, RED
	tilepal 0, RED, WATER, WATER, WATER, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, WATER, WATER, GRAY, GRAY, RED, RED 
	tilepal 0, RED, WATER, RED, RED, WATER, WATER, WATER, WATER
	tilepal 0, WATER, WATER, GRAY, GRAY, GRAY, GRAY, RED, RED
	tilepal 0, WATER, WATER, RED, RED, GRAY, WATER, WATER, WATER
	tilepal 0, WATER, GRAY, RED, RED, YELLOW, YELLOW, RED, RED
	tilepal 0, WATER, WATER, RED, RED, RED, RED, YELLOW, YELLOW
	tilepal 0, RED, RED, RED, RED, GRAY, GRAY, RED, RED

rept 16
	db $ff
endr

	tilepal 1, WATER, WATER, RED, RED, RED, RED, YELLOW, YELLOW
	tilepal 1, RED, RED, RED, RED, RED, RED, RED, RED
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, BROWN, BROWN
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
