	const_def
	const ABILITY_NONE
	const ABILITY_TORRENT ;1
	const ABILITY_OVERGROW ;2
	const ABILITY_BLAZE ;3
	const ABILITY_PRESSURE ;4
	const ABILITY_STATIC ;5
	const ABILITY_LEVITATE ;6
	const ABILITY_SOUNDPROOF ;7
	const ABILITY_POISON_POINT ;8
	const ABILITY_EFFECT_SPORE ;9
	const ABILITY_SWARM ;a
	const ABILITY_SHIELD_DUST ;b
	const ABILITY_LIMBER ;c
	const ABILITY_LIQUID_OOZE ;d
	const ABILITY_GUTS ;e
	const ABILITY_CUTE_CHARM ;f
	const ABILITY_FLAME_BODY ;10
	const ABILITY_HYPER_CUTTER ;11
	const ABILITY_INTIMIDATE ;12
	const ABILITY_CLEAR_BODY ;13
	const ABILITY_ARENA_TRAP ;14
	const ABILITY_DROUGHT ;15
	const ABILITY_DRIZZLE ;16
	const ABILITY_SAND_STREAM ;17
	const ABILITY_SNOW_WARNING ;18
	const ABILITY_SYNCHRONIZE ;19
	const ABILITY_RUN_AWAY ;1a
	const ABILITY_MOODY ;1b
	const ABILITY_SPEED_BOOST ;1c
	const ABILITY_RIVALRY ;1d
	const ABILITY_TRACE ;1e
	const ABILITY_KLUTZ ;1f
	const ABILITY_EARLY_BIRD ;20
	const ABILITY_SHED_SKIN ;21
	const ABILITY_STURDY ;22
	const ABILITY_MAGMA_ARMOR ;23
	const ABILITY_STENCH ;24
	const ABILITY_ILLUMINATE ;25
	const ABILITY_NO_GUARD ;26
	const ABILITY_WHITE_SMOKE ;27
	const ABILITY_VITAL_SPIRIT ;28
	const ABILITY_INSOMNIA ;29
	const ABILITY_SNOW_CLOAK ;2a
	const ABILITY_SAND_VEIL ;2b
	const ABILITY_LIGHTNINGROD ;2c
	const ABILITY_INNER_FOCUS ;2d
	const ABILITY_STEADFAST ;2e
	const ABILITY_ICE_BODY ;2f
	const ABILITY_FLASH_FIRE ;30
	const ABILITY_ROCK_HEAD ;31
	const ABILITY_HEATPROOF ;32
	const ABILITY_SNIPER ;33
	const ABILITY_BATTLE_ARMOR ;34
	const ABILITY_MOLD_BREAKER ;35
	const ABILITY_CHLOROPHYLL ;36
	const ABILITY_SWIFT_SWIM ;37
	const ABILITY_UNBURDEN ;38
	const ABILITY_AFTERMATH ;39
	const ABILITY_OBLIVIOUS ;3a
	const ABILITY_OWN_TEMPO ;3b
	const ABILITY_MAGNET_PULL ;3c
	const ABILITY_KEEN_EYE ;3d
	const ABILITY_STALL ;3e
	const ABILITY_FRISK ;3f
	const ABILITY_THICK_FAT ;40
	const ABILITY_RECKLESS ;41
	const ABILITY_IRON_FIST ;42
	const ABILITY_SOLID_ROCK ;43
	const ABILITY_SERENE_GRACE ;44
	const ABILITY_NATURAL_CURE ;45
	const ABILITY_LEAF_GUARD ;46
	const ABILITY_SCRAPPY ;47
	const ABILITY_WATER_VEIL ;48
	const ABILITY_RAIN_DISH ;49
	const ABILITY_TECHNICIAN ;4a
	const ABILITY_MOTOR_DRIVE ;4b
	const ABILITY_SUPER_LUCK ;4c
	const ABILITY_ADAPTABILITY ;4d
	const ABILITY_WATER_ABSORB ;4e
	const ABILITY_VOLT_ABSORB ;4f
	const ABILITY_DOWNLOAD
	const ABILITY_SUCTION_CUPS
	const ABILITY_IMMUNITY
	const ABILITY_COMPETITIVE
	const ABILITY_HUSTLE
	const ABILITY_HUGE_POWER
	const ABILITY_SIMPLE
	const ABILITY_POISON_HEAL
	const ABILITY_COMPOUNDEYES
	const ABILITY_MARVEL_SCALE
	const ABILITY_PICKUP
	const ABILITY_QUICK_FEET
	const ABILITY_AIR_LOCK
	const ABILITY_TINTED_LENS
	const ABILITY_DRY_SKIN
	const ABILITY_TANGLED_FEET
	const ABILITY_CONTRARY
	const ABILITY_TRUANT
	const ABILITY_NALJO_FURY
	const ABILITY_UNKNOWN
	