	const_def
	const SCGB_BATTLE_GRAYSCALE
	const SCGB_BATTLE_COLORS
	const SCGB_POKEGEAR_PALS
	const SCGB_STATS_SCREEN_HP_PALS
	const SCGB_POKEDEX
	const SCGB_SLOT_MACHINE
	const SCGB_SCROLLINGMENU
	const SCGB_MAPPALS
	const SCGB_0A
	const SCGB_0B
	const SCGB_0E
	const SCGB_POKEDEX_SEARCH_OPTION
	const SCGB_POKEPIC
	const SCGB_PACKPALS
	const SCGB_TRAINER_CARD
	const SCGB_17
	const SCGB_18
	const SCGB_19
	const SCGB_1A
	const SCGB_1B
	const SCGB_FRONTPICPALS
	const SCGB_SECOND_LOGO

SCGB_PARTY_MENU_HP_PALS  EQU -4
SCGB_RAM EQU -1
