	enum_start
	enum pokecenternurse
	enum difficultbookshelf
	enum picturebookshelf
	enum magazinebookshelf
	enum fastcurrent
	enum merchandiseshelf
	enum townmap
	enum mining
	enum jumpingshoes
	enum homepage
	enum smelting
	enum jeweling
	enum trashcan
	enum strengthboulder
	enum smashrock
	enum pokecentersign
	enum martsign
	enum goldenrodrockets
	enum radiotowerrockets
	enum elevatorbutton
	enum daytotext
	enum initializeevents
	enum gymstatue1
	enum gymstatue2
	enum receiveitem
	enum receivetogepiegg
	enum pcscript
	enum gamecornercoinvendor
	enum happinesschecknpc
	enum fieldmovepokepic
