LANDTILE EQU  0
WALLTILE EQU  1
WATRTILE EQU 15

TALK     EQU  1 << 4

const_value SET 1
	const TILESET_NALJO_1 ;1
	const TILESET_NALJO_2 ;2
	const TILESET_RIJON ;3
	const TILESET_HOUSE_1 ;4
	const TILESET_HOUSE_2 ;5
	const TILESET_POKECENTER ;6
	const TILESET_GATE_JOHTO ;7
	const TILESET_PORT ;8
	const TILESET_LAB ;9
	const TILESET_POWER_PLANT ;a
	const TILESET_MART ;b
	const TILESET_MANSION ;c
	const TILESET_GAME_CORNER ;d
	const TILESET_GYM ;e
	const TILESET_KURT_HOUSE ;f
	const TILESET_TRAIN_STATION ;10
	const TILESET_LIGHTHOUSE ;11
	const TILESET_NALJO_RUINS ;12
	const TILESET_HOUSE_3 ;13
	const TILESET_TOWER ;14
	const TILESET_CAVE ;15
	const TILESET_PARK ;16
	const TILESET_PRISON_ROOMS ;17
	const TILESET_18 ;18
	const TILESET_UNDERGROUND ;19
	const TILESET_ICE_PATH ;1a
	const TILESET_CAVE_KANTO ;1b
	const TILESET_FOREST ;1c
	const TILESET_GATE_KANTO ;1d
	const TILESET_TRAINER_HOUSE ;1e
	const TILESET_1F ;1f
	const TILESET_SIDESCROLL ;20
	const TILESET_MAGMA_CAVERNS ;21
	const TILESET_JOHTO ;22
	const TILESET_KANTO ;23
	const TILESET_PACHISI ;24
	const TILESET_HAUNTED_FOREST ;25
	const TILESET_HAUNTED_MANSION ;26
	const TILESET_PSYCHEDELIC ;27
	const TILESET_GYM_CADENCE ;28
	const TILESET_GYM_BROOKLYN ;29
	const TILESET_MAGIKARP_CAVERNS ;2a
	const TILESET_PRISON_MAIN ;2b
	const TILESET_ILEX_FOREST ;2c
	const TILESET_TUNOD ;2d
	const TILESET_GATE ;2e
	const TILESET_CHAMPION_ROOM ;2f
	const TILESET_CAVE2 ;30
	const TILESET_CAVE3 ;31 
	const TILESET_CAVE4 ;32
	const TILESET_CAVE5 ;33
	const TILESET_CAVE6 ;34
	const TILESET_CAVE7 ;35

	const_def
	const PAL_BG_GRAY
	const PAL_BG_RED
	const PAL_BG_GREEN
	const PAL_BG_WATER
	const PAL_BG_YELLOW
	const PAL_BG_BROWN
	const PAL_BG_ROOF
	const PAL_BG_TEXT
