TrainerGroups:
	dw JosiahGroup
	dw BrooklynGroup
	dw RinjiGroup
	dw EdisonGroup
	dw AyakaGroup
	dw CadenceGroup
	dw AndreGroup
	dw BruceGroup
	dw RivalGroup
	dw MuraGroup
	dw YukiGroup
	dw KojiGroup
	dw DaichiGroup
	dw DelinquentFGroup
	dw SoraGroup
	dw LanceGroup
	dw PatrollerGroup
	dw ScientistGroup
	dw YoungsterGroup
	dw SchoolboyGroup
	dw BirdKeeperGroup
	dw LassGroup
	dw CheerleaderGroup
	dw CooltrainerMGroup
	dw CooltrainerFGroup
	dw BeautyGroup
	dw PokemaniacGroup
	dw GruntMGroup
	dw GentlemanGroup
	dw SkierGroup
	dw TeacherGroup
	dw SherylGroup
	dw BugCatcherGroup
	dw FisherGroup
	dw SwimmerMGroup
	dw SwimmerFGroup
	dw SailorGroup
	dw SuperNerdGroup
	dw SilverGroup
	dw GuitaristGroup
	dw HikerGroup
	dw BikerGroup
	dw JoeGroup
	dw BurglarGroup
	dw FirebreatherGroup
	dw JugglerGroup
	dw BlackbeltGroup
	dw PsychicGroup
	dw PicnickerGroup
	dw CamperGroup
	dw SageGroup
	dw MediumGroup
	dw BoarderGroup
	dw PokefanMGroup
	dw DelinquentMGroup
	dw TwinsGroup
	dw PokefanFGroup
	dw RedGroup
	dw BlueGroup
	dw OfficerGroup
	dw MinerGroup
	dw KarpmanGroup
	dw ArcadePCGroup
	dw LilyGroup
	dw LoisGroup
	dw SparkyGroup
	dw GoldGroup
	dw GiovanniGroup
	dw ErnestGroup
	dw KrisGroup
	dw KimonoGirlGroup
	dw BugsyGroup
	dw WhitneyGroup
	dw SabrinaGroup
	dw CandelaGroup
	dw BlancheGroup
	dw SparkGroup
	dw BrownGroup
	dw GuitaristFGroup
