	dba Music_Nothing
	dba Music_TitleScreen
	dba Music_Route1
	dba Music_Route3
	dba Music_Route12
	dba Music_MagnetTrain
	dba Music_KantoGymBattle
	dba Music_KantoTrainerBattle
	dba Music_KantoWildBattle
	dba Music_PokemonCenter
	dba Music_LookHiker
	dba Music_LookLass
	dba Music_LookOfficer
	; dba Music_HealPokemon
	dba Music_LavenderTown
	dba Music_Route2
	dba Music_MtMoon
	dba Music_GameCorner
	dba Music_Bicycle
	dba Music_HallOfFame
	dba Music_ViridianCity
	dba Music_CeladonCity
	dba Music_TrainerVictory
	dba Music_WildPokemonVictory
	dba Music_GymLeaderVictory
	dba Music_MtMoonSquare
	dba Music_Gym
	dba Music_PalletTown
	dba Music_ProfOaksPokemonTalk
	dba Music_ProfOak
	dba Music_LookRival
	dba Music_AfterTheRivalFight
	dba Music_Surf
	dba Music_Evolution
	dba Music_NationalPark
	dba Music_Credits
	dba Music_AzaleaTown
	dba Music_CherrygroveCity
	dba Music_LookKimonoGirl
	dba Music_UnionCave
	dba Music_JohtoWildBattle
	dba Music_JohtoGSC
	dba Music_Route30
	dba Music_EcruteakCity
	dba Music_VioletCity
	dba Music_JohtoGymBattle
	dba Music_ChampionBattle
	dba Music_RivalBattle
	dba Music_RocketBattle
	dba Music_ElmsLab
	dba Music_DarkCave
	dba Music_Route36
	dba Music_SSAqua
	dba Music_LookYoungster
	dba Music_LookBeauty
	dba Music_LookRocket
	dba Music_LookPokemaniac
	dba Music_LookSage
	dba Music_NewBarkTown
	dba Music_GoldenrodCity
	dba Music_VermilionCity
	dba Music_PokemonChannel
	dba Music_TinTower
	dba Music_SproutTower
	dba Music_BurnedTower
	dba Music_Lighthouse
	dba Music_LakeOfRage
	dba Music_IndigoPlateau
	dba Music_Route37
	dba Music_RocketHideout
	dba Music_DragonsDen
	dba Music_SuccessfulCapture
	dba Music_Route26
	dba Music_Mom
	dba Music_VictoryRoad
	dba Music_MainMenu
	dba Music_RuinsOfAlphInterior
	dba Music_RocketTheme
	dba Music_DancingHall
	dba Music_ContestResults
	dba Music_BugCatchingContest
	dba Music_LakeOfRageRocketRadio
	dba Music_Printer
	dba Music_PostCredits

; Crystal adds the following songs:

	dba Music_LookMysticalMan
	dba Music_CrystalOpening
	dba Music_BattleTowerTheme
	dba Music_SuicuneBattle
	dba Music_BattleTowerLobby
	dba Music_MobileCenter
	dba Music_MobileAdapter

; Prism stuff
	dba Music_CeruleanGSC
	dba Music_CinnabarRemix
	dba Music_NuggetBridge
	dba Music_Oreburgh
	dba Music_Route203
	dba Music_Route209
	dba Music_Route210
	dba Music_Route216
	dba Music_EternaForest
	dba Music_Shop
	dba Music_NaljoWildBattle
	dba Music_NaljoTrainerBattle
	dba Music_NaljoGymBattle
	dba Music_PalletBattle
	dba Music_KantoLegend
	dba Music_Route103
	dba Music_TCGClub2
	dba Music_PrismIceCave
	dba Music_PrismTrainerEncounter
	dba Music_PrismToughTrainer2
	dba Music_PrismFemaleTrainer
	dba Music_PrismFemaleTrainer2
	dba Music_HoOhBattle
	dba Music_LugiaBattle
	dba Music_SilphCo
	dba Music_Trade
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Pinballgengarstage_gastly
	dba Music_Pinballgengarstage_haunter
	dba Music_Nothing
	dba Music_Nothing
	dba Music_Nothing
	dba Music_KalosPowerPlant
	dba Music_PokemonTower
	dba Music_SomethingDungeon
	dba Music_LilycoveCity
	dba Music_HoennWildBattle
	dba Music_HoennTrainerBattle
	dba Music_HoennGymBattle
	dba Music_HoennLegend
	dba Music_DreamSequence
