AbilityNames::

	add_name "Torrent"
	add_name "Overgrow"
	add_name "Blaze"
	add_name "Pressure"
	add_name "Static"
	add_name "Levitate"
	add_name "Soundproof"
	add_name "Poison Point" ; 8
	add_name "Effect Spore"
	add_name "Swarm"
	add_name "Shield Dust"
	add_name "Limber"
	add_name "Liquid Ooze"
	add_name "Guts"
	add_name "Cute Charm"
	add_name "Flame Body" ; 10
	add_name "Hyper Cutter"
	add_name "Intimidate"
	add_name "Clear Body"
	add_name "Arena Trap"
	add_name "Drought"
	add_name "Drizzle"
	add_name "Sand Stream"
	add_name "Snow Warning" ; 18
	add_name "Synchronize"
	add_name "Run Away"
	add_name "Moody"
	add_name "Speed Boost"
	add_name "Rivalry"
	add_name "Trace"
	add_name "Klutz"
	add_name "Early Bird"
	add_name "Shed Skin"
	add_name "Sturdy"
	add_name "Magma Armor"
	add_name "Stench"
	add_name "Illuminate"
	add_name "No Guard"
	add_name "White Smoke"
	add_name "Vital Spirit"
	add_name "Insomnia"
	add_name "Snow Cloak"
	add_name "Sand Veil"
	add_name "Lightningrod"
	add_name "Inner Focus"
	add_name "Steadfast"
	add_name "Ice Body"
	add_name "Flash Fire"
	add_name "Rock Head"
	add_name "Heatproof"
	add_name "Sniper"
	add_name "Battle Armor"
	add_name "Mold Breaker"
	add_name "Chlorophyll"
	add_name "Swift Swim"
	add_name "Unburden"
	add_name "Aftermath"
	add_name "Oblivious"
	add_name "Own Tempo"
	add_name "Magnet Pull"
	add_name "Keen Eye"
	add_name "Stall"
	add_name "Frisk"
	add_name "Thick Fat"
	add_name "Reckless"
	add_name "Iron Fist"
	add_name "Solid Rock"
	add_name "Serene Grace"
	add_name "Natural Cure"
	add_name "Leaf Guard"
	add_name "Scrappy"
	add_name "Water Veil"
	add_name "Rain Dish"
	add_name "Technician"
	add_name "Motor Drive"
	add_name "Super Luck"
	add_name "Adaptability"
	add_name "Water Absorb"
	add_name "Volt Absorb"
	add_name "Download"
	add_name "Suction Cups"
	add_name "Immunity"
	add_name "Competitive"
	add_name "Hustle"
	add_name "Huge Power"
	add_name "Simple"
	add_name "Poison Heal"
	add_name "Compoundeyes"
	add_name "Marvel Scale"
	add_name "Pickup"
	add_name "Quick Feet"
	add_name "Air Lock"
	add_name "Tinted Lens"
	add_name "Dry Skin"
	add_name "Tangled Feet"
	add_name "Contrary"
	add_name "Truant"
	add_name "Naljo Fury"
	add_name "?????"
	