	add_name "Pound"
	add_name "Karate Chop"
	add_name "Double Slap"
	add_name "Final Chance"
	add_name "Zen Headbutt"
	add_name "Bulk Up"
	add_name "Fire Punch"
	add_name "Ice Punch"
	add_name "ThunderPunch"
	add_name "Scratch"
	add_name "Fairy Wind"
	add_name "DrainingKiss"
	add_name "Iron Defense"
	add_name "Swords Dance"
	add_name "Cut"
	add_name "Gust"
	add_name "Wing Attack"
	add_name "Whirlwind"
	add_name "Fly"
	add_name "Bug Buzz"
	add_name "Nature Power"
	add_name "Vine Whip"
	add_name "Stomp"
	add_name "Double Kick"
	add_name "Cosmic Power"
	add_name "Laughing Gas"
	add_name "Flare Blitz"
	add_name "Sand-Attack"
	add_name "Headbutt"
	add_name "Prism Spray"
	add_name "Power Ballad"
	add_name "Brave Bird"
	add_name "Tackle"
	add_name "Body Slam"
	add_name "Wrap"
	add_name "Take Down"
	add_name "Hail"
	add_name "Double-Edge"
	add_name "Tail Whip"
	add_name "Poison Sting"
	add_name "Aura Sphere"
	add_name "Pin Missile"
	add_name "Leer"
	add_name "Bite"
	add_name "Growl"
	add_name "Roar"
	add_name "Sing"
	add_name "Supersonic"
	add_name "Dragon Pulse"
	add_name "Disable"
	add_name "Acid"
	add_name "Ember"
	add_name "Flamethrower"
	add_name "Mist"
	add_name "Water Gun"
	add_name "Hydro Pump"
	add_name "Surf"
	add_name "Ice Beam"
	add_name "Blizzard"
	add_name "Psybeam"
	add_name "Bubblebeam"
	add_name "Freeze Burn"
	add_name "Hyper Beam"
	add_name "Peck"
	add_name "Drill Peck"
	add_name "Lava Pool"
	add_name "Drain Punch"
	add_name "Counter"
	add_name "Seismic Toss"
	add_name "Strength"
	add_name "Absorb"
	add_name "Mega Drain"
	add_name "Leech Seed"
	add_name "Growth"
	add_name "Razor Leaf"
	add_name "Solarbeam"
	add_name "PoisonPowder"
	add_name "Stun Spore"
	add_name "Sleep Powder"
	add_name "Hyper Voice"
	add_name "String Shot"
	add_name "Bullet Punch"
	add_name "Fire Spin"
	add_name "Thundershock"
	add_name "Thunderbolt"
	add_name "Thunder Wave"
	add_name "Thunder"
	add_name "Rock Throw"
	add_name "Earthquake"
	add_name "Nasty Plot"
	add_name "Dig"
	add_name "Toxic"
	add_name "Confusion"
	add_name "Psychic"
	add_name "Hypnosis"
	add_name "Dragon Dance"
	add_name "Agility"
	add_name "Quick Attack"
	add_name "Rage"
	add_name "Teleport"
	add_name "Night Shade"
	add_name "Energy Ball"
	add_name "Screech"
	add_name "Double Team"
	add_name "Recover"
	add_name "Harden"
	add_name "Minimize"
	add_name "Smokescreen"
	add_name "Confuse Ray"
	add_name "Head Smash"
	add_name "Defense Curl"
	add_name "Barrier"
	add_name "Light Screen"
	add_name "Haze"
	add_name "Reflect"
	add_name "Focus Energy"
	add_name "Astonish"
	add_name "Metronome"
	add_name "Mirror Move"
	add_name "Selfdestruct"
	add_name "Metallurgy"
	add_name "Lick"
	add_name "Smog"
	add_name "Sludge"
	add_name "Thunder Fang"
	add_name "Fire Blast"
	add_name "Waterfall"
	add_name "Storm Front"
	add_name "Swift"
	add_name "Aqua Jet"
	add_name "Dust Devil"
	add_name "Flash Cannon"
	add_name "Amnesia"
	add_name "Will-O-Wisp"
	add_name "Softboiled"
	add_name "Hi Jump Kick"
	add_name "Mustard Gas"
	add_name "Dream Eater"
	add_name "Poison Gas"
	add_name "Seed Bomb"
	add_name "Leech Life"
	add_name "Nerve Gas"
	add_name "Sky Attack"
	add_name "Transform"
	add_name "Bubble"
	add_name "Dizzy Punch"
	add_name "Spring Buds"
	add_name "Flash"
	add_name "Bass Tremor"
	add_name "Splash"
	add_name "Acid Armor"
	add_name "Night Slash"
	add_name "Explosion"
	add_name "Poison Jab"
	add_name "Signal Beam"
	add_name "Rest"
	add_name "Rock Slide"
	add_name "Meteor Mash"
	add_name "Void Sphere"
	add_name "Conversion"
	add_name "Tri Attack"
	add_name "Dragon Claw"
	add_name "Slash"
	add_name "Substitute"
	add_name "Struggle"
	add_name "Crystal Bolt"
	add_name "Wild Charge"
	add_name "Thief"
	add_name "X-Scissor"
	add_name "Mind Reader"
	add_name "Aerial Ace"
	add_name "Flame Wheel"
	add_name "Iron Head"
	add_name "Curse"
	add_name "Flail"
	add_name "Conversion 2"
	add_name "Aeroblast"
	add_name "Cotton Spore"
	add_name "Reversal"
	add_name "Spite"
	add_name "Powder Snow"
	add_name "Protect"
	add_name "Mach Punch"
	add_name "Scary Face"
	add_name "Feint Attack"
	add_name "Sweet Kiss"
	add_name "Belly Drum"
	add_name "Sludge Bomb"
	add_name "Mud-Slap"
	add_name "Power Gem"
	add_name "Spikes"
	add_name "Zap Cannon"
	add_name "Foresight"
	add_name "Destiny Bond"
	add_name "Perish Song"
	add_name "Icy Wind"
	add_name "Air Slash"
	add_name "Dark Pulse"
	add_name "Earth Power"
	add_name "Outrage"
	add_name "Sandstorm"
	add_name "Giga Drain"
	add_name "Endure"
	add_name "Charm"
	add_name "Rollout"
	add_name "Vaporize"
	add_name "Swagger"
	add_name "Calm Mind"
	add_name "Spark"
	add_name "Fury Cutter"
	add_name "Steel Wing"
	add_name "Mean Look"
	add_name "Attract"
	add_name "Sleep Talk"
	add_name "Heal Bell"
	add_name "Return"
	add_name "Psycho Cut"
	add_name "Frustration"
	add_name "Safeguard"
	add_name "Pain Split"
	add_name "Sacred Fire"
	add_name "Magnitude"
	add_name "DynamicPunch"
	add_name "Megahorn"
	add_name "Dragonbreath"
	add_name "Baton Pass"
	add_name "Encore"
	add_name "Pursuit"
	add_name "Rapid Spin"
	add_name "Sweet Scent"
	add_name "Iron Tail"
	add_name "Metal Claw"
	add_name "Lewisite"
	add_name "Morning Sun"
	add_name "Synthesis"
	add_name "Moonlight"
	add_name "Hidden Power"
	add_name "Cross Chop"
	add_name "Twister"
	add_name "Rain Dance"
	add_name "Sunny Day"
	add_name "Crunch"
	add_name "Boil"
	add_name "Shadow Claw"
	add_name "ExtremeSpeed"
	add_name "AncientPower"
	add_name "Shadow Ball"
	add_name "Future Sight"
	add_name "Rock Smash"
	add_name "Steel Eater"
	add_name "Ghost Hammer"
	add_name "Moonblast"
	add_name "Play Rough"
	add_name "Noise Pulse"
	add_name "@"
