SECTION "Map Headers", ROMX[$4000], BANK[MAP_HEADERS]
MapGroupPointers::
	dw MapGroup1
	dw MapGroup2
	dw MapGroup3
	dw MapGroup4
	dw MapGroup5
	dw MapGroup6
	dw MapGroup7
	dw MapGroup8
	dw MapGroup9
	dw MapGroup10
	dw MapGroup11
	dw MapGroup12
	dw MapGroup13
	dw MapGroup14
	dw MapGroup15
	dw MapGroup16
	dw MapGroup17
	dw MapGroup18
	dw MapGroup19
	dw MapGroup20
	dw MapGroup21
	dw MapGroup22
	dw MapGroup23
	dw MapGroup24
	dw MapGroup25
	dw MapGroup26
	dw MapGroup27
	dw MapGroup28
	dw MapGroup29
	dw MapGroup30
	dw MapGroup31
	dw MapGroup32
	dw MapGroup33
	dw MapGroup34
	dw MapGroup35
	dw MapGroup36
	dw MapGroup37
	dw MapGroup38
	dw MapGroup39
	dw MapGroup40
	dw MapGroup41
	dw MapGroup42
	dw MapGroup43
	dw MapGroup44
	dw MapGroup45
	dw MapGroup46
	dw MapGroup47
	dw MapGroup48
	dw MapGroup49
	dw MapGroup50
	dw MapGroup51
	dw MapGroup52
	dw MapGroup53
	dw MapGroup54
	dw MapGroup55
	dw MapGroup56
	dw MapGroup57
	dw MapGroup58
	dw MapGroup59
	dw MapGroup60
	dw MapGroup61
	dw MapGroup62
	dw MapGroup63
	dw MapGroup64
	dw MapGroup65
	dw MapGroup66
	dw MapGroup67
	dw MapGroup68
	dw MapGroup69
	dw MapGroup70
	dw MapGroup71
	dw MapGroup72
	dw MapGroup73
	dw MapGroup74
	dw MapGroup75
	dw MapGroup76
	dw MapGroup77
	dw MapGroup78
	dw MapGroup79
	dw MapGroup80
	dw MapGroup81
	dw MapGroup82
	dw MapGroup83
	dw MapGroup84
	dw MapGroup85
	dw MapGroup86
	dw MapGroup87
	dw MapGroup88
	dw MapGroup89
	dw MapGroup90
	dw MapGroup91
	dw MapGroup92
	dw MapGroup93
	dw MapGroup94
	dw MapGroup95

MapGroup1:
	map_header IntroOutside, TILESET_RIJON, ROUTE, DUMMY2, MUSIC_NONE, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header IntroCave, TILESET_CAVE4, INDOOR, DUMMY2, MUSIC_NONE, 0, PALETTE_NITE, FISHGROUP_NONE
MapGroup2:
	map_header CaperCity, TILESET_NALJO_2, TOWN, CAPER_CITY, MUSIC_NEW_BARK_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header CaperPokecenter, TILESET_POKECENTER, INDOOR, CAPER_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CaperMart, TILESET_MART, INDOOR, CAPER_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header IlksLab, TILESET_MANSION, INDOOR, CAPER_CITY, MUSIC_PROF_ELM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CaperHouse, TILESET_HOUSE_1, INDOOR, CAPER_CITY, MUSIC_NEW_BARK_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup3:
	map_header OxalisCity, TILESET_NALJO_1, TOWN, OXALIS_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header OxalisPokecenter, TILESET_POKECENTER, INDOOR, OXALIS_CITY, MUSIC_MOBILE_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OxalisMart, TILESET_MART, INDOOR, OXALIS_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header OxalisGym, TILESET_MAGMA_CAVERNS, INDOOR, OXALIS_CITY, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SpritePickerMale, TILESET_GATE, GATE, OXALIS_CITY, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TrainerHouse, TILESET_TRAINER_HOUSE, DUNGEON, OXALIS_CITY, MUSIC_BATTLE_TOWER_LOBBY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TrainerHouseB1F, TILESET_SIDESCROLL, INDOOR, OXALIS_CITY, MUSIC_BATTLE_TOWER_LOBBY, 0, PALETTE_MORN, FISHGROUP_NONE
	map_header HappinessRater, TILESET_HOUSE_1, INDOOR, OXALIS_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header OxalisSalon, TILESET_HOUSE_1, INDOOR, OXALIS_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SpritePickerFemale, TILESET_HOUSE_1, INDOOR, OXALIS_CITY, MUSIC_CHERRYGROVE_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
MapGroup4:
	map_header SpurgeCity, TILESET_NALJO_1, TOWN, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SpurgePokecenter, TILESET_POKECENTER, INDOOR, SPURGE_CITY, MUSIC_MOBILE_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SpurgeMart, TILESET_GAME_CORNER, INDOOR, SPURGE_CITY, MUSIC_MART, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SpurgeHouse, TILESET_HOUSE_1, INDOOR, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Orphanage, TILESET_HOUSE_2, INDOOR, SPURGE_CITY, MUSIC_POST_CREDITS, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SpurgeGameCorner, TILESET_GAME_CORNER, INDOOR, SPURGE_CITY, MUSIC_GAME_CORNER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header ApartmentsF1, TILESET_UNDERGROUND, INDOOR, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ApartmentsF2, TILESET_GATE_JOHTO, INDOOR, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ApartmentsF3, TILESET_MANSION, INDOOR, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Apartments2D, TILESET_HOUSE_2, INDOOR, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Apartments1B, TILESET_HOUSE_1, INDOOR, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Apartments1C, TILESET_HOUSE_1, INDOOR, SPURGE_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SpurgeGym1F, TILESET_GYM, INDOOR, SPURGE_CITY, MUSIC_ROUTE_A, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SpurgeGymB1F, TILESET_CAVE3, INDOOR, SPURGE_CITY, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SpurgeGymB2F, TILESET_CAVE3, INDOOR, SPURGE_CITY, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SpurgeGymB2FSidescroll, TILESET_SIDESCROLL, INDOOR, SPURGE_CITY, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SpurgeGymHouse, TILESET_HOUSE_2, INDOOR, SPURGE_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup5:
	map_header HeathVillage, TILESET_NALJO_1, TOWN, HEATH_VILLAGE, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header HeathInn, TILESET_KURT_HOUSE, INDOOR, HEATH_VILLAGE, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header HeathGym, TILESET_FOREST, CAVE, HEATH_VILLAGE, MUSIC_LAUREL_FOREST, 1, PALETTE_AUTO, FISHGROUP_NONE
	map_header HeathGymGate, TILESET_KURT_HOUSE, GATE, HEATH_VILLAGE, MUSIC_LAUREL_FOREST, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HeathGymHouse, TILESET_KURT_HOUSE, INDOOR, HEATH_VILLAGE, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header HeathGymUnderground, TILESET_MAGMA_CAVERNS, DUNGEON, HEATH_VILLAGE, MUSIC_TIN_TOWER, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header HeathHouseTM13, TILESET_KURT_HOUSE, INDOOR, HEATH_VILLAGE, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header HeathHouseTM30, TILESET_KURT_HOUSE, INDOOR, HEATH_VILLAGE, MUSIC_AZALEA_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HeathHouseWeaver, TILESET_KURT_HOUSE, INDOOR, HEATH_VILLAGE, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header HeathGate, TILESET_GATE, GATE, ROUTE_74, MUSIC_ROUTE_37, 0, PALETTE_DAY, FISHGROUP_NONE
MapGroup6:
	map_header LaurelCity, TILESET_NALJO_1, TOWN, LAUREL_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header LaurelPokecenter, TILESET_POKECENTER, INDOOR, LAUREL_CITY, MUSIC_MOBILE_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LaurelMart, TILESET_MART, INDOOR, LAUREL_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header LaurelGym, TILESET_GYM_BROOKLYN, INDOOR, LAUREL_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header LaurelLab, TILESET_POWER_PLANT, INDOOR, LAUREL_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LaurelNamerater, TILESET_HOUSE_1, INDOOR, LAUREL_CITY, MUSIC_ECRUTEAK_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header LaurelStick, TILESET_HOUSE_1, INDOOR, LAUREL_CITY, MUSIC_ECRUTEAK_CITY, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header LaurelGate, TILESET_GATE, GATE, LAUREL_CITY, MUSIC_ROUTE_30, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MagikarpCavernsMain, TILESET_CAVE3, CAVE, LAUREL_CITY, MUSIC_TIN_TOWER, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MagikarpCavernsRapids, TILESET_MAGIKARP_CAVERNS, CAVE, LAUREL_CITY, MUSIC_TIN_TOWER, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header MagikarpCavernsEnd, TILESET_MAGIKARP_CAVERNS, CAVE, LAUREL_CITY, MUSIC_TIN_TOWER, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup7:
	map_header ToreniaCity, TILESET_NALJO_1, TOWN, TORENIA_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header ToreniaPokecenter, TILESET_POKECENTER, INDOOR, TORENIA_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header ToreniaMart, TILESET_MART, INDOOR, TORENIA_CITY, MUSIC_MART, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ToreniaGym, TILESET_TOWER, INDOOR, TORENIA_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header ToreniaMagnetTrain, TILESET_TRAIN_STATION, INDOOR, TORENIA_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ToreniaPachisi, TILESET_PACHISI, GATE, TORENIA_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ToreniaDrifloomTrade, TILESET_HOUSE_1, INDOOR, TORENIA_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ToreniaCelebrity, TILESET_HOUSE_1, INDOOR, TORENIA_CITY, MUSIC_AZALEA_TOWN, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header ToreniaGate, TILESET_GATE, GATE, TORENIA_CITY, MUSIC_AZALEA_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup8:
	map_header PhaceliaCity, TILESET_NALJO_1, TOWN, PHACELIA_TOWN, MUSIC_OREBURGH, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header PhaceliaPoliceF2, TILESET_PRISON_MAIN, INDOOR, PHACELIA_TOWN, MUSIC_OREBURGH, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhaceliaPoliceF1, TILESET_GATE, INDOOR, PHACELIA_TOWN, MUSIC_OREBURGH, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhaceliaEastExit, TILESET_CAVE7, GATE, PHACELIA_TOWN, MUSIC_OREBURGH, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header PhaceliaPokecenter, TILESET_POKECENTER, INDOOR, PHACELIA_TOWN, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhaceliaMart, TILESET_MART, INDOOR, PHACELIA_TOWN, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhaceliaGym, TILESET_CAVE6, CAVE, PHACELIA_TOWN, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header PhaceliaMoveDeleter, TILESET_HOUSE_1, INDOOR, PHACELIA_TOWN, MUSIC_OREBURGH, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhaceliaSolrockTrade, TILESET_HOUSE_1, INDOOR, PHACELIA_TOWN, MUSIC_OREBURGH, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhaceliaTM20, TILESET_HOUSE_1, INDOOR, PHACELIA_TOWN, MUSIC_OREBURGH, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhaceliaWestExit, TILESET_CAVE6, GATE, PHACELIA_TOWN, MUSIC_OREBURGH, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup9:
	map_header SaxifrageIsland, TILESET_NALJO_1, TOWN, SAXIFRAGE_ISLAND, MUSIC_CINNABAR_ISLAND, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SaxifragePokecenter, TILESET_POKECENTER, INDOOR, SAXIFRAGE_ISLAND, MUSIC_MOBILE_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header SaxifrageMart, TILESET_MART, INDOOR, SAXIFRAGE_ISLAND, MUSIC_MART, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonF1, TILESET_PRISON_MAIN, INDOOR, SAXIFRAGE_ISLAND, MUSIC_SOMETHING_DUNGEON, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonPaths, TILESET_PRISON_MAIN, INDOOR, SAXIFRAGE_ISLAND, MUSIC_SOMETHING_DUNGEON, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaxifrageExits, TILESET_CAVE7, INDOOR, SAXIFRAGE_ISLAND, MUSIC_CINNABAR_ISLAND, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SaxifrageGym, TILESET_GYM_CADENCE, INDOOR, SAXIFRAGE_ISLAND, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SaxifrageWardensHouse, TILESET_HOUSE_1, INDOOR, SAXIFRAGE_ISLAND, MUSIC_CINNABAR_ISLAND, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonBaths, TILESET_PRISON_ROOMS, INDOOR, SAXIFRAGE_ISLAND, MUSIC_SOMETHING_DUNGEON, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonWorkout, TILESET_PRISON_ROOMS, INDOOR, SAXIFRAGE_ISLAND, MUSIC_SOMETHING_DUNGEON, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonCafeteria, TILESET_PRISON_ROOMS, INDOOR, SAXIFRAGE_ISLAND, MUSIC_SOMETHING_DUNGEON, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonElectricChair, TILESET_PRISON_ROOMS, INDOOR, SAXIFRAGE_ISLAND, MUSIC_NONE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonRoof, TILESET_PRISON_ROOMS, INDOOR, SAXIFRAGE_ISLAND, MUSIC_CINNABAR_ISLAND, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header PrisonF2, TILESET_PRISON_MAIN, INDOOR, SAXIFRAGE_ISLAND, MUSIC_SOMETHING_DUNGEON, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PrisonB1F, TILESET_PRISON_MAIN, INDOOR, SAXIFRAGE_ISLAND, MUSIC_SOMETHING_DUNGEON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header PrisonContainment, TILESET_PRISON_MAIN, INDOOR, SAXIFRAGE_ISLAND, MUSIC_NONE, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup10:
	map_header PhloxTown, TILESET_NALJO_2, TOWN, PHLOX_TOWN, MUSIC_ECRUTEAK_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header PhloxPokecenter, TILESET_POKECENTER, INDOOR, PHLOX_TOWN, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhloxMart, TILESET_MART, INDOOR, PHLOX_TOWN, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhloxBingo, TILESET_HOUSE_1, INDOOR, PHLOX_TOWN, MUSIC_ECRUTEAK_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhloxEntry, TILESET_CAVE2, GATE, PHLOX_TOWN, MUSIC_ECRUTEAK_CITY, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header PhloxBarry, TILESET_HOUSE_1, INDOOR, PHLOX_TOWN, MUSIC_ECRUTEAK_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PhloxLabB1F, TILESET_LIGHTHOUSE, CAVE, PHLOX_TOWN, MUSIC_SILPH_CO, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup11:
	map_header AcaniaDocks, TILESET_NALJO_1, TOWN, ACANIA_DOCKS, MUSIC_VIOLET_CITY, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header AcaniaPokecenter, TILESET_POKECENTER, INDOOR, ACANIA_DOCKS, MUSIC_MOBILE_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header AcaniaMart, TILESET_MART, INDOOR, ACANIA_DOCKS, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AcaniaHouse, TILESET_HOUSE_1, INDOOR, ACANIA_DOCKS, MUSIC_VIOLET_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AcaniaTM63, TILESET_HOUSE_1, INDOOR, ACANIA_DOCKS, MUSIC_VIOLET_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AcaniaLighthouseF1, TILESET_NALJO_RUINS, INDOOR, ACANIA_DOCKS, MUSIC_VIOLET_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AcaniaLighthouseF2, TILESET_NALJO_RUINS, INDOOR, ACANIA_DOCKS, MUSIC_VIOLET_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AcaniaGym, TILESET_NALJO_RUINS, INDOOR, ACANIA_DOCKS, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup12:
	map_header Route68, TILESET_NALJO_1, ROUTE, ROUTE_68, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_OCEAN
MapGroup13:
	map_header Route69, TILESET_NALJO_1, TOWN, ROUTE_69, MUSIC_ROUTE_D, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route69Gate, TILESET_GATE, GATE, ROUTE_69, MUSIC_ROUTE_D, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route69IlkBrotherHouse, TILESET_HOUSE_2, INDOOR, ROUTE_69, MUSIC_ROUTE_D, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup14:
	map_header Route70, TILESET_NALJO_2, ROUTE, ROUTE_70, MUSIC_ROUTE_D, 0, PALETTE_AUTO, FISHGROUP_SHORE
MapGroup15:
	map_header Route71, TILESET_NALJO_2, ROUTE, ROUTE_71, MUSIC_ROUTE_G, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route71b, TILESET_NALJO_1, ROUTE, ROUTE_71, MUSIC_ROUTE_G, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup16:
	map_header Route72, TILESET_NALJO_1, ROUTE, ROUTE_72, MUSIC_ROUTE_G, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route72Gate, TILESET_GATE, GATE, ROUTE_72, MUSIC_ROUTE_G, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup17:
	map_header Route73, TILESET_NALJO_1, TOWN, ROUTE_73, MUSIC_ROUTE_H, 0, PALETTE_AUTO, FISHGROUP_LAKE
MapGroup18:
	map_header Route74, TILESET_NALJO_1, ROUTE, ROUTE_74, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup19:
	map_header Route75, TILESET_NALJO_1, ROUTE, ROUTE_75, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_SHORE
MapGroup20:
	map_header Route76, TILESET_NALJO_1, ROUTE, ROUTE_76, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup21:
	map_header Route77, TILESET_NALJO_1, ROUTE, ROUTE_77, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route77Pokecenter, TILESET_POKECENTER, INDOOR, ROUTE_77, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route77Jewelers, TILESET_KURT_HOUSE, INDOOR, ROUTE_77, MUSIC_ROUTE_37, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route77DaycareHouse, TILESET_HOUSE_1, INDOOR, ROUTE_77, MUSIC_ROUTE_37, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route77DaycareGarden, TILESET_NALJO_1, ROUTE, ROUTE_77, MUSIC_ROUTE_37, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup22:
	map_header Route78, TILESET_NALJO_1, ROUTE, ROUTE_78, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route78EastExit, TILESET_CAVE7, GATE, ROUTE_78, MUSIC_ROUTE_36, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup23:
	map_header Route79, TILESET_NALJO_1, ROUTE, ROUTE_79, MUSIC_ROUTE_12, 0, PALETTE_AUTO, FISHGROUP_OCEAN
MapGroup24:
	map_header Route80, TILESET_NALJO_1, ROUTE, ROUTE_80, MUSIC_ROUTE_36, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route80Phancero, TILESET_ICE_PATH, CAVE, ROUTE_80, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header Route80Nobu, TILESET_KURT_HOUSE, INDOOR, ROUTE_80, MUSIC_DANCING_HALL, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup25:
	map_header Route81, TILESET_NALJO_1, ROUTE, ROUTE_81, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route81Northgate, TILESET_GATE, GATE, ROUTE_81, MUSIC_ROUTE_26, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route81Pokecenter, TILESET_POKECENTER, INDOOR, ROUTE_81, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route81Eastgate, TILESET_GATE, GATE, ROUTE_81, MUSIC_ROUTE_26, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route81Goodrod, TILESET_HOUSE_1, INDOOR, ROUTE_81, MUSIC_ROUTE_26, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup26:
	map_header Route82, TILESET_NALJO_1, ROUTE, ROUTE_82, MUSIC_LAKE_OF_RAGE, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route82Gate, TILESET_GATE, GATE, ROUTE_82, MUSIC_LAKE_OF_RAGE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route82Cave, TILESET_CAVE7, CAVE, ROUTE_82, MUSIC_LAKE_OF_RAGE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header Route82Monkey, TILESET_CAVE7, CAVE, ROUTE_82, MUSIC_NONE, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup27:
	map_header Route83, TILESET_NALJO_1, ROUTE, ROUTE_83, MUSIC_ROUTE_H, 0, PALETTE_AUTO, FISHGROUP_LAKE
MapGroup28:
	map_header Route84, TILESET_NALJO_2, ROUTE, ROUTE_84, MUSIC_ROUTE_I, 0, PALETTE_AUTO, FISHGROUP_POND
MapGroup29:
	map_header Route85, TILESET_NALJO_2, ROUTE, ROUTE_85, MUSIC_ROUTE_26, 0, PALETTE_AUTO, FISHGROUP_OCEAN
MapGroup30:
	map_header Route86, TILESET_NALJO_1, TOWN, ROUTE_86, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route86Pokecenter, TILESET_POKECENTER, INDOOR, ROUTE_86, MUSIC_MOBILE_CENTER, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header Route86Dock, TILESET_PORT, ROUTE, ROUTE_86, MUSIC_SS_AQUA, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route86DockExit, TILESET_GATE_KANTO, GATE, ROUTE_86, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route86UndergroundPath, TILESET_GATE_KANTO, GATE, ROUTE_86, MUSIC_NONE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header FarawayIslandOutside, TILESET_TUNOD, TOWN, FARAWAY_ISLAND, MUSIC_NONE, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header FarawayIslandInside, TILESET_TUNOD, TOWN, FARAWAY_ISLAND, MUSIC_NONE, 0, PALETTE_AUTO, FISHGROUP_SHORE
MapGroup31:
	map_header AcquaStart, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaTutorial, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 0, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaExitChamber, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaPhloxEntrance, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaHiTide, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaMedTide, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaLowTide, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaRoom, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header AcquaLabBasementPath, TILESET_CAVE2, CAVE, ACQUA_MINES, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
MapGroup32:
	map_header MoundF1, TILESET_CAVE, CAVE, MOUND_CAVE, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MoundB2F, TILESET_CAVE, CAVE, MOUND_CAVE, MUSIC_DARK_CAVE, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header MoundB3F, TILESET_CAVE, CAVE, MOUND_CAVE, MUSIC_DARK_CAVE, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header MoundB1F, TILESET_SIDESCROLL, CAVE, MOUND_CAVE, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MoundUpperArea, TILESET_CAVE, CAVE, MOUND_CAVE, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_CAVE
MapGroup33:
	map_header LaurelForestMain, TILESET_FOREST, CAVE, LAUREL_FOREST, MUSIC_NATURE_FOREST, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header LaurelForestBeach, TILESET_FOREST, CAVE, LAUREL_FOREST, MUSIC_NATURE_FOREST, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header LaurelForestCharizardCave, TILESET_CAVE3, CAVE, LAUREL_FOREST, MUSIC_ROUTE_2, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header LaurelForestLab, TILESET_POWER_PLANT, INDOOR, LAUREL_FOREST, MUSIC_ROCKET_HIDEOUT, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header LaurelForestGates, TILESET_GATE, GATE, LAUREL_FOREST, MUSIC_NATURE_FOREST, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header LaurelForestPokemonOnly, TILESET_FOREST, CAVE, LAUREL_FOREST, MUSIC_NATURE_FOREST, 0, PALETTE_NITE, FISHGROUP_NONE
MapGroup34:
	map_header MilosF1, TILESET_CAVE6, CAVE, MILOS_CATACOMBS, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MilosB1F, TILESET_CAVE6, CAVE, MILOS_CATACOMBS, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header MilosB2F, TILESET_SIDESCROLL, CAVE, MILOS_CATACOMBS, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header MilosB2Fb, TILESET_SIDESCROLL, CAVE, MILOS_CATACOMBS, MUSIC_DRAGONS_DEN, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header MilosTowerClimb, TILESET_SIDESCROLL, ROUTE, MILOS_CATACOMBS, MUSIC_BURNED_TOWER, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header MilosGreenOrb, TILESET_GYM_BROOKLYN, DUNGEON, MILOS_CATACOMBS, MUSIC_BURNED_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MilosRayquaza, TILESET_GYM_BROOKLYN, DUNGEON, MILOS_CATACOMBS, MUSIC_NONE, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup35:
	map_header ProvincialPark, TILESET_FOREST, CAVE, PROVINICIAL_PARK, MUSIC_NATIONAL_PARK, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header ProvincialParkContest, TILESET_FOREST, CAVE, PROVINICIAL_PARK, MUSIC_BUG_CATCHING_CONTEST, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header ProvincialParkGate, TILESET_GATE, GATE, PROVINICIAL_PARK, MUSIC_NATIONAL_PARK, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup36:
	map_header MagmaF1, TILESET_MAGMA_CAVERNS, CAVE, MAGMA_CAVERNS, MUSIC_SPROUT_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MagmaPalletPathB1F, TILESET_MAGMA_CAVERNS, CAVE, MAGMA_CAVERNS, MUSIC_SPROUT_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MagmaRooms, TILESET_MAGMA_CAVERNS, CAVE, MAGMA_CAVERNS, MUSIC_SPROUT_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MagmaPalletPath1F, TILESET_MAGMA_CAVERNS, CAVE, MAGMA_CAVERNS, MUSIC_SPROUT_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MagmaMinecart, TILESET_CAVE, CAVE, MAGMA_CAVERNS, MUSIC_SPROUT_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MagmaGroudon, TILESET_MAGMA_CAVERNS, CAVE, MAGMA_CAVERNS, MUSIC_SPROUT_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MagmaItemRoom, TILESET_MAGMA_CAVERNS, CAVE, MAGMA_CAVERNS, MUSIC_SPROUT_TOWER, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup37:
	map_header RuinsB1F, TILESET_HOUSE_3, CAVE, NALJO_RUINS, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsOutside, TILESET_HOUSE_3, CAVE, NALJO_RUINS, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RuinsEntry, TILESET_CAVE7, GATE, NALJO_RUINS, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RuinsF1, TILESET_HOUSE_3, CAVE, NALJO_RUINS, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RuinsF2, TILESET_HOUSE_3, CAVE, NALJO_RUINS, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RuinsF3, TILESET_HOUSE_3, CAVE, NALJO_RUINS, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RuinsF4, TILESET_HOUSE_3, CAVE, NALJO_RUINS, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RuinsF5, TILESET_HOUSE_3, CAVE, NALJO_RUINS, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RuinsRoof, TILESET_HOUSE_3, ROUTE, NALJO_RUINS, MUSIC_UNION_CAVE, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup38:
	map_header ClathriteB1F, TILESET_ICE_PATH, CAVE, CLATHRITE_TUNNEL, MUSIC_CLATHRITE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header ClathriteB2F, TILESET_ICE_PATH, CAVE, CLATHRITE_TUNNEL, MUSIC_CLATHRITE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header Clathrite1F, TILESET_CAVE6, CAVE, CLATHRITE_TUNNEL, MUSIC_CLATHRITE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header ClathriteKyogre, TILESET_ICE_PATH, INDOOR, CLATHRITE_TUNNEL, MUSIC_CLATHRITE, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup39:
	map_header NaljoBorderEast, TILESET_CAVE_KANTO, CAVE, NALJO_BORDER, MUSIC_ROUTE_3, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header NaljoBorderWest, TILESET_GATE, GATE, NALJO_BORDER, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header NaljoBorderWarpRoom, TILESET_UNDERGROUND, INDOOR, NALJO_BORDER, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup40:
MapGroup41:
	map_header LongTunnelPath, TILESET_CAVE_KANTO, CAVE, TUNNEL, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header LongTunnelSidescroll, TILESET_SIDESCROLL, DUNGEON, TUNNEL, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup42:
	map_header SeashoreCity, TILESET_RIJON, TOWN, SEASHORE_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header BrownsHouseF1, TILESET_HOUSE_2, INDOOR, SEASHORE_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BrownsHouseF2, TILESET_HOUSE_2, INDOOR, SEASHORE_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SeashoreGym, TILESET_RIJON, INDOOR, SEASHORE_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_SHORE
	map_header SeashoreMura, TILESET_HOUSE_1, INDOOR, SEASHORE_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup43:
	map_header GravelTown, TILESET_RIJON, TOWN, GRAVEL_TOWN, MUSIC_PALLET_TOWN, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header GravelMart, TILESET_MART, INDOOR, GRAVEL_TOWN, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header JensLab, TILESET_LAB, INDOOR, GRAVEL_TOWN, MUSIC_PROF_ELM, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup44:
	map_header MersonCity, TILESET_RIJON, TOWN, MERSON_CITY, MUSIC_LAVENDER_TOWN, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header MersonGym, TILESET_PORT, INDOOR, MERSON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_LAKE
	map_header MersonMart, TILESET_MART, INDOOR, MERSON_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MersonPokecenter, TILESET_POKECENTER, INDOOR, MERSON_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MersonHouse, TILESET_HOUSE_1, INDOOR, MERSON_CITY, MUSIC_LAVENDER_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MersonBirdHouse, TILESET_HOUSE_1, INDOOR, MERSON_CITY, MUSIC_LAVENDER_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MersonHouse2, TILESET_HOUSE_1, INDOOR, MERSON_CITY, MUSIC_LAVENDER_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MersonGoldTokenExchange, TILESET_GYM, INDOOR, MERSON_CITY, MUSIC_LAVENDER_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup45:
	map_header HaywardCity, TILESET_RIJON, TOWN, HAYWARD_CITY, MUSIC_CERULEAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header HaywardMartF1, TILESET_MART, INDOOR, HAYWARD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardMartF2, TILESET_MART, INDOOR, HAYWARD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardMartF3, TILESET_MART, INDOOR, HAYWARD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardMartF4, TILESET_MART, INDOOR, HAYWARD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardMartF5, TILESET_MART, INDOOR, HAYWARD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardMartElevator, TILESET_TRAINER_HOUSE, INDOOR, HAYWARD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardMartF6, TILESET_MART, INDOOR, HAYWARD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardEarthquakeLab, TILESET_POWER_PLANT, INDOOR, HAYWARD_CITY, MUSIC_CERULEAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardPokecenter, TILESET_POKECENTER, INDOOR, HAYWARD_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardMawile, TILESET_HOUSE_1, INDOOR, HAYWARD_CITY, MUSIC_CERULEAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HaywardHouse, TILESET_HOUSE_1, INDOOR, HAYWARD_CITY, MUSIC_CERULEAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup46:
	map_header OwsauriCity, TILESET_RIJON, TOWN, OWSAURI_CITY, MUSIC_CERULEAN_CITY, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header OwsauriGym, TILESET_GYM, INDOOR, OWSAURI_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header OwsauriGameCorner, TILESET_GAME_CORNER, INDOOR, OWSAURI_CITY, MUSIC_GAME_CORNER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header OwsauriMart, TILESET_MART, INDOOR, OWSAURI_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header OwsauriPokecenter, TILESET_POKECENTER, INDOOR, OWSAURI_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header OwsauriNamerater, TILESET_HOUSE_1, INDOOR, OWSAURI_CITY, MUSIC_CERULEAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header OwsauriHouse, TILESET_HOUSE_1, INDOOR, OWSAURI_CITY, MUSIC_CERULEAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header OwsauriStatEXP, TILESET_HOUSE_1, INDOOR, OWSAURI_CITY, MUSIC_CERULEAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup47:
	map_header MoragaTown, TILESET_RIJON, TOWN, MORAGA_TOWN, MUSIC_CELADON_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header MoragaGym, TILESET_TRAIN_STATION, INDOOR, MORAGA_TOWN, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MoragaDiner, TILESET_GAME_CORNER, INDOOR, MORAGA_TOWN, MUSIC_CELADON_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MoragaGateUnderground, TILESET_GATE_KANTO, GATE, MORAGA_TOWN, MUSIC_CELADON_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MoragaMart, TILESET_MART, INDOOR, MORAGA_TOWN, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MoragaPokecenter, TILESET_POKECENTER, INDOOR, MORAGA_TOWN, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MoragaHouse, TILESET_HOUSE_1, INDOOR, MORAGA_TOWN, MUSIC_CELADON_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MoragaTMMachine, TILESET_HOUSE_1, INDOOR, MORAGA_TOWN, MUSIC_CELADON_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup48:
	map_header JaeruCity, TILESET_RIJON, TOWN, JAERU_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header JaeruGym, TILESET_LAB, INDOOR, JAERU_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header JaeruGate, TILESET_GATE_KANTO, GATE, JAERU_CITY, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header JaeruPokecenter, TILESET_POKECENTER, INDOOR, JAERU_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header JaeruMart, TILESET_MART, INDOOR, JAERU_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header JaeruGuardSupplier, TILESET_HOUSE_1, INDOOR, JAERU_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup49:
	map_header BotanCity, TILESET_RIJON, TOWN, BOTAN_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header BotanMart, TILESET_MART, INDOOR, BOTAN_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BotanPokecenter, TILESET_POKECENTER, INDOOR, BOTAN_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BotanHouse, TILESET_HOUSE_1, INDOOR, BOTAN_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BotanMagnetTrain, TILESET_TRAIN_STATION, INDOOR, BOTAN_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BotanPachisi, TILESET_PACHISI, INDOOR, BOTAN_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup50:
	map_header CastroValley, TILESET_RIJON, TOWN, CASTRO_VALLEY, MUSIC_VERMILION_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header CastroDockPath, TILESET_GATE_KANTO, GATE, CASTRO_VALLEY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CastroGym, TILESET_KURT_HOUSE, INDOOR, CASTRO_VALLEY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CastroGate, TILESET_GATE_KANTO, GATE, CASTRO_VALLEY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CastroMart, TILESET_MART, INDOOR, CASTRO_VALLEY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CastroPokecenter, TILESET_POKECENTER, INDOOR, CASTRO_VALLEY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CastroMansion, TILESET_UNDERGROUND, INDOOR, CASTRO_VALLEY, MUSIC_DARK_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header CastroTyrogueTrade, TILESET_HOUSE_1, INDOOR, CASTRO_VALLEY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CastroSuperRod, TILESET_HOUSE_1, INDOOR, CASTRO_VALLEY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header CastroDock, TILESET_PORT, ROUTE, CASTRO_VALLEY, MUSIC_SS_AQUA, 0, PALETTE_AUTO, FISHGROUP_SHORE
MapGroup51:
	map_header EagulouCity, TILESET_RIJON, TOWN, EAGULOU_CITY, MUSIC_CINNABAR_ISLAND, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header EagulouParkGate, TILESET_GATE_KANTO, GATE, EAGULOU_CITY, MUSIC_CINNABAR_ISLAND, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header EagulouPark1, TILESET_ILEX_FOREST, ROUTE, EAGULOU_PARK, MUSIC_EVOLUTION, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header EagulouCity2, TILESET_ILEX_FOREST, ROUTE, EAGULOU_PARK, MUSIC_EVOLUTION, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header EagulouCity3, TILESET_ILEX_FOREST, ROUTE, EAGULOU_PARK, MUSIC_EVOLUTION, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header EagulouMart, TILESET_MART, INDOOR, EAGULOU_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header EagulouPokecenter, TILESET_POKECENTER, INDOOR, EAGULOU_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header EagulouGymF1, TILESET_CAVE_KANTO, INDOOR, EAGULOU_CITY, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header EagulouGymB1F, TILESET_PRISON_MAIN, INDOOR, EAGULOU_CITY, MUSIC_LIGHTHOUSE, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup52:
	map_header RijonLeagueOutside, TILESET_JOHTO, TOWN, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header RijonLeagueInside, TILESET_POKECENTER, INDOOR, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RijonLeagueYuki, TILESET_ICE_PATH, CAVE, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RijonLeagueSora, TILESET_GYM_BROOKLYN, INDOOR, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RijonLeagueDaichi, TILESET_CAVE4, CAVE, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RijonLeagueMura, TILESET_TRAIN_STATION, INDOOR, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RijonLeagueLance, TILESET_TRAINER_HOUSE, CAVE, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header RijonLeagueParty, TILESET_RIJON, ROUTE, DUMMY2, MUSIC_NATIONAL_PARK, 0, PALETTE_NITE, FISHGROUP_NONE
	map_header RijonLeagueChampionRoom, TILESET_CHAMPION_ROOM, INDOOR, RIJON_LEAGUE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup53:
	map_header Route47, TILESET_RIJON, TOWN, ROUTE_47, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
MapGroup54:
	map_header Route48, TILESET_RIJON, TOWN, ROUTE_48, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
MapGroup55:
	map_header Route49, TILESET_RIJON, TOWN, ROUTE_49, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route49Gate, TILESET_GATE_KANTO, GATE, ROUTE_49, MUSIC_ROUTE_3, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup56:
	map_header Route50, TILESET_RIJON, TOWN, ROUTE_50, MUSIC_ROUTE_25, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route50Gate, TILESET_GATE_KANTO, GATE, ROUTE_50, MUSIC_ROUTE_25, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup57:
	map_header Route51, TILESET_RIJON, TOWN, ROUTE_51, MUSIC_ROUTE_25, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup58:
	map_header Route52, TILESET_RIJON, TOWN, ROUTE_52, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route52Gate, TILESET_GATE_KANTO, GATE, ROUTE_52, MUSIC_ROUTE_1, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route52GateUnderground, TILESET_GATE_KANTO, INDOOR, ROUTE_52, MUSIC_ROUTE_1, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route52House, TILESET_HOUSE_1, INDOOR, ROUTE_52, MUSIC_ROUTE_1, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup59:
	map_header Route53, TILESET_RIJON, TOWN, ROUTE_53, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup60:
	map_header Route54, TILESET_RIJON, TOWN, ROUTE_54, MUSIC_ROUTE_1, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup61:
	map_header Route55, TILESET_RIJON, TOWN, ROUTE_55, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route55GateUnderground, TILESET_GATE_KANTO, GATE, ROUTE_55, MUSIC_ROUTE_3, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup62:
	map_header Route56, TILESET_RIJON, TOWN, ROUTE_56, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header Route56Gate, TILESET_GATE_KANTO, GATE, ROUTE_56, MUSIC_ROUTE_3, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route56GateUnderground, TILESET_GATE_KANTO, GATE, ROUTE_56, MUSIC_ROUTE_3, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup63:
	map_header Route57, TILESET_RIJON, TOWN, ROUTE_57, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route57Gym, TILESET_UNDERGROUND, INDOOR, ROUTE_57, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup64:
	map_header Route58, TILESET_RIJON, TOWN, ROUTE_58, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route58Gate, TILESET_GATE_KANTO, GATE, ROUTE_58, MUSIC_ROUTE_3, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup65:
	map_header Route59, TILESET_RIJON, TOWN, ROUTE_59, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route59Gate, TILESET_GATE_KANTO, GATE, ROUTE_59, MUSIC_ROUTE_3, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SilphWarehouseF1, TILESET_POWER_PLANT, INDOOR, ROUTE_59, MUSIC_SILPH_CO, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SilphWarehouseB1F, TILESET_UNDERGROUND, INDOOR, ROUTE_59, MUSIC_SILPH_CO, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SilphWarehouseF2, TILESET_POWER_PLANT, TOWN, ROUTE_59, MUSIC_SILPH_CO, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup66:
	map_header Route60, TILESET_RIJON, TOWN, ROUTE_60, MUSIC_ROUTE_25, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route60Gate, TILESET_GATE_KANTO, GATE, ROUTE_60, MUSIC_ROUTE_25, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header PowerPlant, TILESET_POWER_PLANT, DUNGEON, POWER_PLANT, MUSIC_KALOS_POWERPLANT, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup67:
	map_header Route61, TILESET_RIJON, TOWN, ROUTE_61, MUSIC_ROUTE_25, 0, PALETTE_AUTO, FISHGROUP_POND
	map_header Route61GateSouth, TILESET_GATE_KANTO, GATE, ROUTE_61, MUSIC_ROUTE_25, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route61GateNorth, TILESET_GATE_KANTO, GATE, ROUTE_61, MUSIC_ROUTE_25, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route61House, TILESET_HOUSE_1, INDOOR, ROUTE_61, MUSIC_ROUTE_25, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route61House2, TILESET_HOUSE_1, INDOOR, ROUTE_61, MUSIC_ROUTE_25, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup68:
	map_header Route62, TILESET_RIJON, TOWN, ROUTE_62, MUSIC_ROUTE_25, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header Route62Gate, TILESET_GATE_KANTO, GATE, ROUTE_62, MUSIC_ROUTE_25, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup69:
	map_header Route63, TILESET_RIJON, TOWN, ROUTE_63, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup70:
	map_header Route64, TILESET_RIJON, TOWN, ROUTE_64, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup71:
	map_header Route65, TILESET_JOHTO, ROUTE, ROUTE_65, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_LAKE
MapGroup72:
	map_header Route66, TILESET_RIJON, TOWN, ROUTE_66, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_SHORE
MapGroup73:
	map_header Route67, TILESET_JOHTO, ROUTE, ROUTE_67, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_LAKE
	map_header Route67Pokecenter, TILESET_POKECENTER, INDOOR, ROUTE_67, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route67House, TILESET_UNDERGROUND, INDOOR, ROUTE_67, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route67Gate, TILESET_GATE_KANTO, INDOOR, ROUTE_67, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup74:
	map_header MersonCaveB1F, TILESET_CAVE_KANTO, CAVE, MERSON_CAVE, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MersonCaveB2F, TILESET_CAVE_KANTO, CAVE, MERSON_CAVE, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MersonCaveB3F, TILESET_CAVE_KANTO, CAVE, MERSON_CAVE, MUSIC_MT_MOON, 1, PALETTE_DARK, FISHGROUP_NONE
MapGroup75:
	map_header SilkTunnelB1F, TILESET_CAVE_KANTO, CAVE, SILK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SilkTunnelB2F, TILESET_CAVE_KANTO, CAVE, SILK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MtBoulderB1F, TILESET_CAVE_KANTO, CAVE, MT_BOULDER, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SilkTunnel1F, TILESET_CAVE_KANTO, CAVE, SILK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SilkTunnelB3F, TILESET_CAVE_KANTO, CAVE, SILK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SilkTunnelB4F, TILESET_CAVE_KANTO, CAVE, SILK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_DARK, FISHGROUP_NONE
	map_header SilkTunnelB5F, TILESET_CAVE_KANTO, CAVE, SILK_TUNNEL, MUSIC_MT_MOON, 1, PALETTE_DARK, FISHGROUP_NONE
MapGroup76:
	map_header CastroForest, TILESET_FOREST, CAVE, CASTRO_FOREST, MUSIC_ROUTE_2, 1, PALETTE_NITE, FISHGROUP_POND
	map_header CastroForestGateSouth, TILESET_GATE_KANTO, GATE, CASTRO_FOREST, MUSIC_ROUTE_2, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup77:
	map_header MtBoulderB2F, TILESET_CAVE_KANTO, CAVE, MT_BOULDER, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup78:
	map_header RijonUndergroundHorizontal, TILESET_GATE_KANTO, GATE, TUNNEL, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RijonUndergroundVertical, TILESET_GATE_KANTO, GATE, TUNNEL, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header RijonHiddenBasement, TILESET_UNDERGROUND, GATE, RIJON_LEAGUE, MUSIC_MT_MOON_SQUARE, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup79:
	map_header SenecaCavernsF1, TILESET_CAVE_KANTO, CAVE, SENECA_CAVERNS, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header SenecaCavernsB1F, TILESET_CAVE_KANTO, CAVE, SENECA_CAVERNS, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_CAVE
	map_header SenecaCavernsB2F, TILESET_CAVE_KANTO, CAVE, SENECA_CAVERNS, MUSIC_VICTORY_ROAD, 1, PALETTE_NITE, FISHGROUP_CAVE
MapGroup80:
	map_header HauntedForestGate, TILESET_GATE_KANTO, GATE, HAUNTED_FOREST, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header HauntedForest, TILESET_HAUNTED_FOREST, CAVE, HAUNTED_FOREST, MUSIC_HAUNTED_FOREST, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header HauntedMansion, TILESET_HAUNTED_MANSION, CAVE, HAUNTED_FOREST, MUSIC_HAUNTED_MANSION, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header DreamSequence, TILESET_PSYCHEDELIC, INDOOR, HAUNTED_FOREST, MUSIC_DREAM_SEQUENCE, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header DreamNewBark, TILESET_JOHTO, INDOOR, HAUNTED_FOREST, MUSIC_SS_AQUA, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header HauntedMansionBasement, TILESET_PRISON_MAIN, CAVE, HAUNTED_FOREST, MUSIC_HAUNTED_MANSION, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup81:
	map_header AzaleaTown, TILESET_JOHTO, TOWN, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header AzaleaPokecenter, TILESET_POKECENTER, INDOOR, AZALEA_TOWN, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AzaleaMart, TILESET_MART, INDOOR, AZALEA_TOWN, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AzaleaGym, TILESET_GYM, INDOOR, AZALEA_TOWN, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AzaleaCharcoal, TILESET_HOUSE_1, INDOOR, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AzaleaKurt, TILESET_KURT_HOUSE, INDOOR, AZALEA_TOWN, MUSIC_AZALEA_TOWN, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header AzaleaKurtBasement, TILESET_KURT_HOUSE, TOWN, AZALEA_TOWN, MUSIC_BURNED_TOWER, 1, PALETTE_NITE, FISHGROUP_NONE
MapGroup82:
	map_header IlexForest, TILESET_ILEX_FOREST, CAVE, ILEX_FOREST, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_POND
	map_header IlexForestGate, TILESET_GATE_JOHTO, GATE, ILEX_FOREST, MUSIC_ROUTE_30, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup83:
	map_header Route34, TILESET_JOHTO, ROUTE, ROUTE_34, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header Route34Gate, TILESET_GATE_JOHTO, GATE, ILEX_FOREST, MUSIC_ROUTE_30, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup84:
	map_header GoldenrodCity, TILESET_JOHTO, TOWN, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header GoldenrodCape, TILESET_JOHTO, TOWN, GOLDENROD_CAPE, MUSIC_ROUTE_30, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header GoldenrodCapeGate, TILESET_GATE_JOHTO, GATE, GOLDENROD_CAPE, MUSIC_ROUTE_30, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodPokecenter, TILESET_POKECENTER, INDOOR, GOLDENROD_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodMart, TILESET_MART, INDOOR, GOLDENROD_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodMagnetTrain, TILESET_TRAIN_STATION, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodGym, TILESET_GYM, INDOOR, GOLDENROD_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodUndergroundEntryA, TILESET_GYM, INDOOR, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodUndergroundEntryB, TILESET_GYM, INDOOR, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodUnderground, TILESET_GATE_JOHTO, DUNGEON, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodSwitches, TILESET_GYM, INDOOR, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header GoldenrodStorage, TILESET_UNDERGROUND, INDOOR, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header GoldenrodMartB1F, TILESET_UNDERGROUND, INDOOR, GOLDENROD_CITY, MUSIC_UNION_CAVE, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header GoldenrodGameCorner, TILESET_GAME_CORNER, INDOOR, GOLDENROD_CITY, MUSIC_GAME_CORNER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodHappinessMoveTeacher, TILESET_HOUSE_1, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header GoldenrodBill, TILESET_HOUSE_1, INDOOR, GOLDENROD_CITY, MUSIC_GOLDENROD_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup85:
	map_header SaffronCity, TILESET_KANTO, TOWN, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 0, PALETTE_AUTO, FISHGROUP_NONE
	map_header SaffronPokecenter, TILESET_POKECENTER, INDOOR, SAFFRON_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronMart, TILESET_MART, INDOOR, SAFFRON_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronMagnetTrain, TILESET_TRAIN_STATION, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronGates, TILESET_GATE_KANTO, GATE, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SilphCo, TILESET_POWER_PLANT, INDOOR, SAFFRON_CITY, MUSIC_SILPH_CO, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SilphCoB1F, TILESET_CAVE_KANTO, CAVE, SAFFRON_CITY, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SaffronMrPsychic, TILESET_HOUSE_1, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronFightingDojo, TILESET_KURT_HOUSE, INDOOR, SAFFRON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronGym, TILESET_UNDERGROUND, INDOOR, SAFFRON_CITY, MUSIC_GYM, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SaffronCopycatsHouse, TILESET_HOUSE_2, INDOOR, SAFFRON_CITY, MUSIC_VIRIDIAN_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup86:
MapGroup87:
	map_header BattleArcadeLobby, TILESET_TRAINER_HOUSE, DUNGEON, CHAMPION_ISLE, MUSIC_BATTLE_TOWER_LOBBY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleArcadeBattleroom, TILESET_TRAINER_HOUSE, DUNGEON, CHAMPION_ISLE, MUSIC_BATTLE_TOWER_LOBBY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup88:
	map_header EmberBrook, TILESET_JOHTO, ROUTE, EMBER_BROOK, MUSIC_ROUTE_H, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header EmberBrookGate, TILESET_GATE_JOHTO, GATE, EMBER_BROOK, MUSIC_ROUTE_H, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MtEmberEntrance, TILESET_CAVE_KANTO, CAVE, MT_EMBER, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MtEmberRoom1, TILESET_CAVE_KANTO, CAVE, MT_EMBER, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MtEmberRoom2, TILESET_CAVE_KANTO, CAVE, MT_EMBER, MUSIC_MT_MOON, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header MtEmber, TILESET_KANTO, ROUTE, MT_EMBER, MUSIC_MT_MOON, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup89:
	map_header SouthSoutherly, TILESET_TUNOD, ROUTE, SOUTH_SOUTHERLY, MUSIC_ROUTE_TUNOD, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header TunodWaterway, TILESET_TUNOD, ROUTE, TUNOD_WATERWAY, MUSIC_ROUTE_TUNOD, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header SoutherlyCity, TILESET_TUNOD, TOWN, SOUTHERLY_CITY, MUSIC_VERMILION_CITY, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header SoutherlyGym, TILESET_GYM, INDOOR, SOUTHERLY_CITY, MUSIC_GYM, 1, PALETTE_NITE, FISHGROUP_NONE
	map_header SoutherlyPokecenter, TILESET_POKECENTER, INDOOR, SOUTHERLY_CITY, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SoutherlyMart, TILESET_MART, INDOOR, SOUTHERLY_CITY, MUSIC_MART, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SoutherlyHouse, TILESET_HOUSE_1, INDOOR, SOUTHERLY_CITY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SoutherlyHouse2, TILESET_HOUSE_1, INDOOR, SOUTHERLY_CITY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SoutherlyBattleHouse, TILESET_POWER_PLANT, INDOOR, SOUTHERLY_CITY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header SoutherlyAirport, TILESET_GATE_JOHTO, GATE, SOUTHERLY_CITY, MUSIC_VERMILION_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header Route87, TILESET_TUNOD, ROUTE, ROUTE_87, MUSIC_ROUTE_3, 0, PALETTE_AUTO, FISHGROUP_NONE
MapGroup90:
	map_header PokecenterBackroom, TILESET_POKECENTER, INDOOR, SPECIAL_MAP, MUSIC_MOBILE_CENTER, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TradeCenter, TILESET_GATE_JOHTO, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleCenter, TILESET_GATE_JOHTO, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header TimeCapsule, TILESET_GATE_JOHTO, INDOOR, SPECIAL_MAP, MUSIC_CHERRYGROVE_CITY, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup91:
	map_header BattleTowerEntrance, TILESET_TRAINER_HOUSE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTowerElevator, TILESET_TRAINER_HOUSE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTowerHallway, TILESET_TRAINER_HOUSE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header BattleTowerBattleRoom, TILESET_TRAINER_HOUSE, INDOOR, BATTLE_TOWER, MUSIC_BATTLE_TOWER_THEME, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup92:
	map_header PhloxLab1F, TILESET_LIGHTHOUSE, INDOOR, PHLOX_TOWN, MUSIC_KALOS_POWERPLANT, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PhloxLab2F, TILESET_LIGHTHOUSE, INDOOR, PHLOX_TOWN, MUSIC_KALOS_POWERPLANT, 0, PALETTE_DAY, FISHGROUP_NONE
	map_header PhloxLab3F, TILESET_LIGHTHOUSE, INDOOR, PHLOX_TOWN, MUSIC_KALOS_POWERPLANT, 0, PALETTE_DAY, FISHGROUP_NONE
MapGroup93:
	map_header PhanceroRoom, TILESET_KANTO, INDOOR, HAUNTED_FOREST, MUSIC_NONE, 0, PALETTE_DAY, FISHGROUP_NONE
MapGroup94:
	map_header MysteryZone, TILESET_KANTO, TOWN, MYSTERY_ZONE, MUSIC_INDIGO_PLATEAU, 0, PALETTE_AUTO, FISHGROUP_SHORE
	map_header MysteryZoneLeagueLobby, TILESET_POKECENTER, INDOOR, MYSTERY_ZONE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MysteryZoneLeagueBrown, TILESET_GYM, INDOOR, MYSTERY_ZONE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MysteryZoneLeagueGold, TILESET_GYM, INDOOR, MYSTERY_ZONE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MysteryZoneLeagueRed, TILESET_GYM, INDOOR, MYSTERY_ZONE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
	map_header MysteryZoneLeagueAirport, TILESET_POKECENTER, INDOOR, MYSTERY_ZONE, MUSIC_INDIGO_PLATEAU, 1, PALETTE_DAY, FISHGROUP_NONE
MapGroup95:
	map_header SeviiIsland1, TILESET_KANTO, ROUTE, SPECIAL_MAP, MUSIC_NONE, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header SeviiIsland2, TILESET_KANTO, ROUTE, SPECIAL_MAP, MUSIC_NONE, 0, PALETTE_AUTO, FISHGROUP_OCEAN
	map_header SeviiIsland3, TILESET_KANTO, ROUTE, SPECIAL_MAP, MUSIC_NONE, 0, PALETTE_AUTO, FISHGROUP_OCEAN
