SECTION "Pokemon Sprite Pointers", ROMX, BANK[POKEMON_SPRITE_POINTERS]

PokemonOWSpritePointers::
	dba BulbasaurOWSprite
	dba IvysaurOWSprite
	dba VenusaurOWSprite
	dba CharmanderOWSprite
	dba CharmeleonOWSprite
	dba CharizardOWSprite
	dba SquirtleOWSprite
	dba WartortleOWSprite
	dba BlastoiseOWSprite
	dba CaterpieOWSprite
	dba MetapodOWSprite
	dba ButterfreeOWSprite
	dba ChinglingOWSprite
	dba ChimechoOWSprite
	dba TorkoalOWSprite
	dba PidgeyOWSprite
	dba PidgeottoOWSprite
	dba PidgeotOWSprite
	dba TaillowOWSprite
	dba SwellowOWSprite
	dba SpearowOWSprite
	dba FearowOWSprite
	dba BunearyOWSprite
	dba LopunnyOWSprite
	dba PikachuOWSprite
	dba RaichuOWSprite
	dba ShinxOWSprite
	dba LuxioOWSprite
	dba LuxrayOWSprite
	dba ElectrikeOWSprite
	dba ManectricOWSprite
	dba SnoruntOWSprite
	dba GlalieOWSprite
	dba FroslassOWSprite
	dba VolbeatOWSprite
	dba IllumiseOWSprite
	dba VulpixOWSprite
	dba NinetalesOWSprite
	dba JigglypuffOWSprite
	dba WigglytuffOWSprite
	dba ZubatOWSprite
	dba GolbatOWSprite
	dba AronOWSprite
	dba LaironOWSprite
	dba AggronOWSprite
	dba ParasOWSprite
	dba ParasectOWSprite
	dba VenonatOWSprite
	dba VenomothOWSprite
	dba BronzorOWSprite
	dba BronzongOWSprite
	dba SkorupiOWSprite
	dba DrapionOWSprite
	dba CranidosOWSprite
	dba RampardosOWSprite
	dba ShieldonOWSprite
	dba BastiodonOWSprite
	dba GrowlitheOWSprite
	dba ArcanineOWSprite
	dba WhismurOWSprite
	dba LoudredOWSprite
	dba ExploudOWSprite
	dba AbraOWSprite
	dba KadabraOWSprite
	dba AlakazamOWSprite
	dba MachopOWSprite
	dba MachokeOWSprite
	dba MachampOWSprite
	dba BellsproutOWSprite
	dba WeepinbellOWSprite
	dba VictreebelOWSprite
	dba TentacoolOWSprite
	dba TentacruelOWSprite
	dba GeodudeOWSprite
	dba GravelerOWSprite
	dba GolemOWSprite
	dba PonytaOWSprite
	dba RapidashOWSprite
	dba SlowpokeOWSprite
	dba SlowbroOWSprite
	dba MagnemiteOWSprite
	dba MagnetonOWSprite
	dba MagnezoneOWSprite
	dba DrifloonOWSprite
	dba DrifblimOWSprite
	dba SableyeOWSprite
	dba SpiritombOWSprite
	dba ShuppetOWSprite
	dba BanetteOWSprite
	dba DuskullOWSprite
	dba DusclopsOWSprite
	dba GastlyOWSprite
	dba HaunterOWSprite
	dba GengarOWSprite
	dba OnixOWSprite
	dba LunatoneOWSprite
	dba SolrockOWSprite
	dba VibravaOWSprite
	dba FlygonOWSprite
	dba MakuhitaOWSprite
	dba HariyamaOWSprite
	dba ExeggcuteOWSprite
	dba ExeggutorOWSprite
	dba CacneaOWSprite
	dba CacturneOWSprite
	dba HitmonleeOWSprite
	dba HitmonchanOWSprite
	dba TrapinchOWSprite
	dba KoffingOWSprite
	dba WeezingOWSprite
	dba RhyhornOWSprite
	dba RhydonOWSprite
	dba ChanseyOWSprite
	dba TangelaOWSprite
	dba KangaskhanOWSprite
	dba TangrowthOWSprite
	dba MawileOWSprite
	dba GoldeenOWSprite
	dba SeakingOWSprite
	dba LotadOWSprite
	dba LombreOWSprite
	dba LudicoloOWSprite
	dba ScytherOWSprite
	dba RelicanthOWSprite
	dba ElectabuzzOWSprite
	dba MagmarOWSprite
	dba ElectivireOWSprite
	dba MagmortarOWSprite
	dba MagikarpOWSprite
	dba GyaradosOWSprite
	dba AbsolOWSprite
	dba DittoOWSprite
	dba EeveeOWSprite
	dba VaporeonOWSprite
	dba JolteonOWSprite
	dba FlareonOWSprite
	dba PorygonOWSprite
	dba VaraneousOWSprite
	dba LileepOWSprite
	dba CradilyOWSprite
	dba AnorithOWSprite
	dba ArmaldoOWSprite
	dba SnorlaxOWSprite
	dba ArticunoOWSprite
	dba ZapdosOWSprite
	dba MoltresOWSprite
	dba BeldumOWSprite
	dba MetangOWSprite
	dba MetagrossOWSprite
	dba MewtwoOWSprite
	dba MewOWSprite
	dba ChikoritaOWSprite
	dba BayleefOWSprite
	dba MeganiumOWSprite
	dba CyndaquilOWSprite
	dba QuilavaOWSprite
	dba TyphlosionOWSprite
	dba TotodileOWSprite
	dba CroconawOWSprite
	dba FeraligatrOWSprite
	dba SentretOWSprite
	dba FurretOWSprite
	dba RaltsOWSprite
	dba KirliaOWSprite
	dba GardevoirOWSprite
	dba GalladeOWSprite
	dba SpinarakOWSprite
	dba AriadosOWSprite
	dba CrobatOWSprite
	dba ChinchouOWSprite
	dba LanturnOWSprite
	dba PichuOWSprite
	dba CarnivineOWSprite
	dba IgglybuffOWSprite
	dba TogepiOWSprite
	dba TogeticOWSprite
	dba NatuOWSprite
	dba XatuOWSprite
	dba MareepOWSprite
	dba FlaaffyOWSprite
	dba AmpharosOWSprite
	dba TogekissOWSprite
	dba MarillOWSprite
	dba AzumarillOWSprite
	dba NumelOWSprite
	dba CameruptOWSprite
	dba WailmerOWSprite
	dba WailordOWSprite
	dba SurskitOWSprite
	dba MasquerainOWSprite
	dba ShroomishOWSprite
	dba BreloomOWSprite
	dba YanmaOWSprite
	dba YanmegaOWSprite
	dba LeafeonOWSprite
	dba EspeonOWSprite
	dba UmbreonOWSprite
	dba GlaceonOWSprite
	dba SlowkingOWSprite
	dba MisdreavusOWSprite
	dba MismagiusOWSprite
	dba SwabluOWSprite
	dba AltariaOWSprite
	dba PinecoOWSprite
	dba ForretressOWSprite
	dba RhyperiorOWSprite
	dba GligarOWSprite
	dba SteelixOWSprite
	dba GliscorOWSprite
	dba FeebasOWSprite
	dba MiloticOWSprite
	dba ScizorOWSprite
	dba RioluOWSprite
	dba LucarioOWSprite
	dba SneaselOWSprite
	dba TeddiursaOWSprite
	dba UrsaringOWSprite
	dba SlugmaOWSprite
	dba MagcargoOWSprite
	dba SwinubOWSprite
	dba PiloswineOWSprite
	dba GibleOWSprite
	dba GabiteOWSprite
	dba GarchompOWSprite
	dba BagonOWSprite
	dba ShelgonOWSprite
	dba SalamenceOWSprite
	dba HoundourOWSprite
	dba HoundoomOWSprite
	dba MamoswineOWSprite
	dba PhanpyOWSprite
	dba DonphanOWSprite
	dba Porygon2OWSprite
	dba PorygonzOWSprite
	dba WeavileOWSprite
	dba TyrogueOWSprite
	dba HitmontopOWSprite
	dba FambacoOWSprite
	dba ElekidOWSprite
	dba MagbyOWSprite
	dba SylveonOWSprite
	dba BlisseyOWSprite
	dba GroudonOWSprite
	dba KyogreOWSprite
	dba RayquazaOWSprite
	dba LarvitarOWSprite
	dba PupitarOWSprite
	dba TyranitarOWSprite
	dba LugiaOWSprite
	dba HoohOWSprite
	dba RaiwatoOWSprite
	dba PhanceroOWSprite
	dbw 0, 0 ; Egg
	dba LibabeelOWSprite
	dba BulbasaurOWSprite
	dba BulbasaurOWSprite
