command: macro
	enum \1_command
\1 equs "db \1_command"
endm

	enum_start 1

	command checkturn
	command checkobedience
	command usedmovetext
	command doturn
	command critical
	command damagestats
	command typematchup
	command damagevariation
	command checkhit
	command lowersub
	command hittargetnosub
	command raisesub
	command failuretext
	command checkfaint
	command criticaltext
	command supereffectivetext
	command checkdestinybond
	command buildopponentrage
	command poisontarget
	command sleeptarget
	command draintarget
	command eatdream
	command burntarget
	command freezetarget
	command paralyzetarget
	command selfdestruct
	command mirrormove
	command statup
	command statdown
	command ___dummy_move_command_6
	command conversion
	command resetstats
	command forceswitch
	command endloop
	command flinchtarget
	command ___dummy_move_command_2
	command recoil
	command mist
	command focusenergy
	command confuse
	command confusetarget
	command heal
	command transform
	command screen
	command poison
	command paralyze
	command burn
	command substitute
	command rechargenextturn
	command metronome
	command leechseed
	command splash
	command disable
	command cleartext
	command charge
	command checkcharge
	command traptarget
	command bulkup
	command cosmicpower
	command calmmind
	command rampage
	command checkrampage
	command constantdamage
	command counter
	command encore
	command ___dummy_move_command_3
	command conversion2
	command lockon
	command defrostopponent
	command sleeptalk
	command destinybond
	command spite
	command falseswipe
	command healbell
	command kingsrock
	command ___dummy_move_command_4
	command ___dummy_move_command_5
	command thief
	command arenatrap
	command nightmare
	command defrost
	command curse
	command protect
	command spikes
	command foresight
	command perishsong
	command startsandstorm
	command starthail
	command endure
	command checkcurl
	command rolloutpower
	command finalchance
	command furycutter
	command attract
	command happinesspower
	command ___dummy_move_command_9
	command damagecalc
	command frustrationpower
	command safeguard
	command checksafeguard
	command getmagnitude
	command batonpass
	command pursuit
	command clearhazards
	command healmorn
	command healday
	command healnite
	command hiddenpower
	command startrain
	command startsun
	command attackup
	command defenseup
	command speedup
	command specialattackup
	command specialdefenseup
	command accuracyup
	command evasionup
	command attackup2
	command defenseup2
	command speedup2
	command specialattackup2
	command specialdefenseup2
	command accuracyup2
	command evasionup2
	command attackdown
	command defensedown
	command speeddown
	command specialattackdown
	command specialdefensedown
	command accuracydown
	command evasiondown
	command attackdown2
	command defensedown2
	command speeddown2
	command specialattackdown2
	command specialdefensedown2
	command accuracydown2
	command evasiondown2
	command statupmessage
	command statdownmessage
	command statupfailtext
	command statdownfailtext
	command effectchance
	command statdownanim
	command statupanim
	command switchturn
	command ___dummy_move_command_7
	command ___dummy_move_command_8
	command rage
	command doubleflyingdamage
	command doubleundergrounddamage
	command checkfuturesight
	command futuresight
	command doubleminimizedamage
	command skipsuncharge
	command thunderaccuracy
	command teleport
	command ___dummy_move_command_1
	command resettypematchup
	command allstatsup
	command raisesubnoanim
	command lowersubnoanim
	command clearmissdamage
	command movedelay
	command hittarget
	command tristatuschance
	command supereffectivelooptext
	command startloop
	command curl
	command lavapool
	command metallurgy
	command vaporize
	command prismspray
	command freezeburnchance
	command naturepower
	command checkpowder
	command painsplit
	command bellydrum
	command dragondance
	command growth
	command defrostfoe
	command laughinggas

	enum_start -1, -1
	command endmove
	command endturn
