INCLUDE "gfx/overworld/pokemon/sprites.asm"
INCLUDE "gfx/overworld/pokemon/sprite_pointers.asm"

SECTION "Sprites 1", ROMX, BANK[SPRITES_1]

AndreSpriteGFX::        INCBIN "gfx/overworld/leaders/andre.2bpp.lz"
BruceSpriteGFX::        INCBIN "gfx/overworld/leaders/bruce.2bpp.lz"
ErnestSpriteGFX::       INCBIN "gfx/overworld/leaders/ernest.2bpp.lz"
KojiSpriteGFX::         INCBIN "gfx/overworld/leaders/koji.2bpp.lz"
SparkSpriteGFX::        INCBIN "gfx/overworld/leaders/spark.2bpp.lz"
AyakaSpriteGFX::        INCBIN "gfx/overworld/leaders/ayaka.2bpp.lz"
GiovanniSpriteGFX::     INCBIN "gfx/overworld/leaders/giovanni.2bpp.lz"
KrisSpriteGFX::         INCBIN "gfx/overworld/leaders/kris.2bpp.lz"
RinjiSpriteGFX::        INCBIN "gfx/overworld/leaders/rinji.2bpp.lz"
SparkySpriteGFX::       INCBIN "gfx/overworld/leaders/sparky.2bpp.lz"
BlancheSpriteGFX::      INCBIN "gfx/overworld/leaders/blanche.2bpp.lz"
CadenceSpriteGFX::      INCBIN "gfx/overworld/leaders/cadence.2bpp.lz"
GoldSpriteGFX::         INCBIN "gfx/overworld/leaders/gold.2bpp.lz"
CandelaSpriteGFX::      INCBIN "gfx/overworld/leaders/candela.2bpp.lz"
JoeSpriteGFX::          INCBIN "gfx/overworld/leaders/joe.2bpp.lz"
LilySpriteGFX::         INCBIN "gfx/overworld/leaders/lily.2bpp.lz"
SheralSpriteGFX::       INCBIN "gfx/overworld/leaders/sheral.2bpp.lz"
YukiSpriteGFX::         INCBIN "gfx/overworld/leaders/yuki.2bpp.lz"
BrooklynSpriteGFX::     INCBIN "gfx/overworld/leaders/brooklyn.2bpp.lz"
DaichiSpriteGFX::       INCBIN "gfx/overworld/leaders/daichi.2bpp.lz"
JosiahSpriteGFX::       INCBIN "gfx/overworld/leaders/josiah.2bpp.lz"
LoisSpriteGFX::         INCBIN "gfx/overworld/leaders/lois.2bpp.lz"
SilverLeaderSpriteGFX:: INCBIN "gfx/overworld/leaders/silver.2bpp.lz"
BrownSpriteGFX::        INCBIN "gfx/overworld/leaders/brown.2bpp.lz"
EdisonSpriteGFX::       INCBIN "gfx/overworld/leaders/edison.2bpp.lz"
KarpmanSpriteGFX::      INCBIN "gfx/overworld/leaders/karpman.2bpp.lz"
MuraSpriteGFX::         INCBIN "gfx/overworld/leaders/mura.2bpp.lz"
SoraSpriteGFX::         INCBIN "gfx/overworld/leaders/sora.2bpp.lz"

SECTION "Sprites 2", ROMX, BANK[SPRITES_2]

R_PsychicSpriteGFX::           INCBIN "gfx/overworld/rijon/r_psychic.2bpp.lz"
R_RockerSpriteGFX::            INCBIN "gfx/overworld/rijon/r_rocker.2bpp.lz"
R_SailorSpriteGFX::            INCBIN "gfx/overworld/rijon/r_sailor.2bpp.lz"
R_ScientistSpriteGFX::         INCBIN "gfx/overworld/rijon/r_scientist.2bpp.lz"
R_SwimmerSpriteGFX::           INCBIN "gfx/overworld/rijon/r_swimmer.2bpp.lz"
R_TamerSpriteGFX::             INCBIN "gfx/overworld/rijon/r_tamer.2bpp.lz"
R_YoungsterSpriteGFX::         INCBIN "gfx/overworld/rijon/r_youngster.2bpp.lz"

SECTION "Sprites 3", ROMX, BANK[SPRITES_3]

Player0SpriteGFX::             INCBIN "gfx/overworld/p0.2bpp.lz"
Player0BikeSpriteGFX::         INCBIN "gfx/overworld/p0bike.2bpp.lz"
GameboyKidSpriteGFX::          INCBIN "gfx/overworld/002.2bpp.lz"
SilverSpriteGFX::              INCBIN "gfx/overworld/003.2bpp.lz"
OakSpriteGFX::                 INCBIN "gfx/overworld/004.2bpp.lz"
RedSpriteGFX::                 INCBIN "gfx/overworld/leaders/red.2bpp.lz"
BlueSpriteGFX::                INCBIN "gfx/overworld/leaders/blue.2bpp.lz"
BillSpriteGFX::                INCBIN "gfx/overworld/007.2bpp.lz"
ElderSpriteGFX::               INCBIN "gfx/overworld/008.2bpp.lz"
JanineSpriteGFX::              INCBIN "gfx/overworld/009.2bpp.lz"
KurtSpriteGFX::                INCBIN "gfx/overworld/010.2bpp.lz"
MomSpriteGFX::                 INCBIN "gfx/overworld/011.2bpp.lz"
BlaineSpriteGFX::              INCBIN "gfx/overworld/012.2bpp.lz"
RedsMomSpriteGFX::             INCBIN "gfx/overworld/013.2bpp.lz"
DaisySpriteGFX::               INCBIN "gfx/overworld/014.2bpp.lz"
ElmSpriteGFX::                 INCBIN "gfx/overworld/015.2bpp.lz"
WillSpriteGFX::                INCBIN "gfx/overworld/016.2bpp.lz"
FalknerSpriteGFX::             INCBIN "gfx/overworld/017.2bpp.lz"
WhitneySpriteGFX::             INCBIN "gfx/overworld/leaders/whitney.2bpp.lz"
BugsySpriteGFX::               INCBIN "gfx/overworld/leaders/bugsy.2bpp.lz"
MortySpriteGFX::               INCBIN "gfx/overworld/020.2bpp.lz"
ChuckSpriteGFX::               INCBIN "gfx/overworld/021.2bpp.lz"
JasmineSpriteGFX::             INCBIN "gfx/overworld/022.2bpp.lz"
PryceSpriteGFX::               INCBIN "gfx/overworld/023.2bpp.lz"
ClairSpriteGFX::               INCBIN "gfx/overworld/024.2bpp.lz"
BrockSpriteGFX::               INCBIN "gfx/overworld/025.2bpp.lz"
KarenSpriteGFX::               INCBIN "gfx/overworld/026.2bpp.lz"
BrunoSpriteGFX::               INCBIN "gfx/overworld/027.2bpp.lz"
MistySpriteGFX::               INCBIN "gfx/overworld/028.2bpp.lz"
LanceSpriteGFX::               INCBIN "gfx/overworld/leaders/lance.2bpp.lz"
SabrinaSpriteGFX::             INCBIN "gfx/overworld/leaders/sabrina.2bpp.lz"
CooltrainerMSpriteGFX::        INCBIN "gfx/overworld/034.2bpp.lz"
CooltrainerFSpriteGFX::        INCBIN "gfx/overworld/035.2bpp.lz"
BugCatcherSpriteGFX::          INCBIN "gfx/overworld/036.2bpp.lz"
TwinSpriteGFX::                INCBIN "gfx/overworld/037.2bpp.lz"
YoungsterSpriteGFX::           INCBIN "gfx/overworld/038.2bpp.lz"
LassSpriteGFX::                INCBIN "gfx/overworld/039.2bpp.lz"
TeacherSpriteGFX::             INCBIN "gfx/overworld/040.2bpp.lz"
BuenaSpriteGFX::               INCBIN "gfx/overworld/041.2bpp.lz"
SuperNerdSpriteGFX::           INCBIN "gfx/overworld/042.2bpp.lz"
RockerSpriteGFX::              INCBIN "gfx/overworld/043.2bpp.lz"
BeautySpriteGFX::              INCBIN "gfx/overworld/beauty.2bpp.lz"
PokefanMSpriteGFX::            INCBIN "gfx/overworld/044.2bpp.lz"

SECTION "Sprites 4", ROMX, BANK[SPRITES_4]

PokefanFSpriteGFX::            INCBIN "gfx/overworld/045.2bpp.lz"
GrampsSpriteGFX::              INCBIN "gfx/overworld/046.2bpp.lz"
GrannySpriteGFX::              INCBIN "gfx/overworld/047.2bpp.lz"
SwimmerGuySpriteGFX::          INCBIN "gfx/overworld/048.2bpp.lz"
SwimmerGirlSpriteGFX::         INCBIN "gfx/overworld/049.2bpp.lz"
BigSnorlaxSpriteGFX::          INCBIN "gfx/overworld/050.2bpp.lz"
SurfingPikachuSpriteGFX::      INCBIN "gfx/overworld/051.2bpp.lz"
RocketSpriteGFX::              INCBIN "gfx/overworld/052.2bpp.lz"
RocketGirlSpriteGFX::          INCBIN "gfx/overworld/053.2bpp.lz"
NurseSpriteGFX::               INCBIN "gfx/overworld/054.2bpp.lz"
LinkReceptionistSpriteGFX::    INCBIN "gfx/overworld/055.2bpp.lz"
ClerkSpriteGFX::               INCBIN "gfx/overworld/056.2bpp.lz"
FisherSpriteGFX::              INCBIN "gfx/overworld/057.2bpp.lz"
FishingGuruSpriteGFX::         INCBIN "gfx/overworld/058.2bpp.lz"
ScientistSpriteGFX::           INCBIN "gfx/overworld/059.2bpp.lz"
KimonoGirlSpriteGFX::          INCBIN "gfx/overworld/060.2bpp.lz"
SageSpriteGFX::                INCBIN "gfx/overworld/061.2bpp.lz"
UnusedGuySpriteGFX::           INCBIN "gfx/overworld/062.2bpp.lz"
GentlemanSpriteGFX::           INCBIN "gfx/overworld/063.2bpp.lz"
BlackBeltSpriteGFX::           INCBIN "gfx/overworld/064.2bpp.lz"
ReceptionistSpriteGFX::        INCBIN "gfx/overworld/065.2bpp.lz"
OfficerSpriteGFX::             INCBIN "gfx/overworld/066.2bpp.lz"
CalSpriteGFX::                 INCBIN "gfx/overworld/067.2bpp.lz"
SlowpokeSpriteGFX::            INCBIN "gfx/overworld/068.2bpp.lz"
CaptainSpriteGFX::             INCBIN "gfx/overworld/069.2bpp.lz"
BigLaprasSpriteGFX::           INCBIN "gfx/overworld/070.2bpp.lz"
GymGuySpriteGFX::              INCBIN "gfx/overworld/071.2bpp.lz"
SailorSpriteGFX::              INCBIN "gfx/overworld/072.2bpp.lz"
BikerSpriteGFX::               INCBIN "gfx/overworld/073.2bpp.lz"
PharmacistSpriteGFX::          INCBIN "gfx/overworld/074.2bpp.lz"
MonsterSpriteGFX::             INCBIN "gfx/overworld/075.2bpp.lz"
FairySpriteGFX::               INCBIN "gfx/overworld/076.2bpp.lz"
BirdSpriteGFX::                INCBIN "gfx/overworld/077.2bpp.lz"
DragonSpriteGFX::              INCBIN "gfx/overworld/078.2bpp.lz"
BigOnixSpriteGFX::             INCBIN "gfx/overworld/079.2bpp.lz"
N64SpriteGFX::                 INCBIN "gfx/overworld/080.2bpp.lz"
SudowoodoSpriteGFX::           INCBIN "gfx/overworld/081.2bpp.lz"
SurfSpriteGFX::                INCBIN "gfx/overworld/082.2bpp.lz"
PokeBallSpriteGFX::            INCBIN "gfx/overworld/083.2bpp.lz"
PokedexSpriteGFX::             INCBIN "gfx/overworld/084.2bpp.lz"
PaperSpriteGFX::               INCBIN "gfx/overworld/085.2bpp.lz"
VirtualBoySpriteGFX::          INCBIN "gfx/overworld/086.2bpp.lz"
OldLinkReceptionistSpriteGFX:: INCBIN "gfx/overworld/087.2bpp.lz"
RockSpriteGFX::                INCBIN "gfx/overworld/088.2bpp.lz"
BoulderSpriteGFX::             INCBIN "gfx/overworld/089.2bpp.lz"
SnesSpriteGFX::                INCBIN "gfx/overworld/090.2bpp.lz"
FamicomSpriteGFX::             INCBIN "gfx/overworld/091.2bpp.lz"
FruitTreeSpriteGFX::           INCBIN "gfx/overworld/092.2bpp.lz"
GoldTrophySpriteGFX::          INCBIN "gfx/overworld/093.2bpp.lz"
SilverTrophySpriteGFX::        INCBIN "gfx/overworld/094.2bpp.lz"
Player1SpriteGFX::             INCBIN "gfx/overworld/p1.2bpp.lz"
Player1BikeSpriteGFX::         INCBIN "gfx/overworld/p1bike.2bpp.lz"
KurtOutsideSpriteGFX::         INCBIN "gfx/overworld/097.2bpp.lz"
SuicuneSpriteGFX::             INCBIN "gfx/overworld/098.2bpp.lz"
EnteiSpriteGFX::               INCBIN "gfx/overworld/099.2bpp.lz"
RaikouSpriteGFX::              INCBIN "gfx/overworld/100.2bpp.lz"
StandingYoungsterSpriteGFX::   INCBIN "gfx/overworld/101.2bpp.lz"
BoarderSpriteGFX::             INCBIN "gfx/overworld/boarder.2bpp.lz"
PsychicSpriteGFX::             INCBIN "gfx/overworld/psychic.2bpp.lz"
SchoolboySpriteGFX::           INCBIN "gfx/overworld/schoolboy.2bpp.lz"
JugglerSpriteGFX::             INCBIN "gfx/overworld/juggler.2bpp.lz"

SECTION "Sprites 5", ROMX, BANK[SPRITES_5]

PokemaniacSpriteGFX::          INCBIN "gfx/overworld/pokemaniac.2bpp.lz"
FirebreatherSpriteGFX::        INCBIN "gfx/overworld/firebreather.2bpp.lz"
HikerSpriteGFX::               INCBIN "gfx/overworld/hiker.2bpp.lz"
PicnickerSpriteGFX::           INCBIN "gfx/overworld/picnicker.2bpp.lz"
CamperSpriteGFX::              INCBIN "gfx/overworld/camper.2bpp.lz"
BirdkeeperSpriteGFX::          INCBIN "gfx/overworld/birdkeeper.2bpp.lz"
R_BeautySpriteGFX::            INCBIN "gfx/overworld/rijon/r_beauty.2bpp.lz"
R_BikerSpriteGFX::             INCBIN "gfx/overworld/rijon/r_biker.2bpp.lz"
R_BirdkeeperSpriteGFX::        INCBIN "gfx/overworld/rijon/r_birdkeeper.2bpp.lz"
R_BlackbeltSpriteGFX::         INCBIN "gfx/overworld/rijon/r_blackbelt.2bpp.lz"
R_BugcatcherSpriteGFX::        INCBIN "gfx/overworld/rijon/r_bugcatcher.2bpp.lz"
R_BurglerSpriteGFX::           INCBIN "gfx/overworld/rijon/r_burgler.2bpp.lz"
R_ChannelerSpriteGFX::         INCBIN "gfx/overworld/rijon/r_channeler.2bpp.lz"
R_CooltrainerFSpriteGFX::      INCBIN "gfx/overworld/rijon/r_cooltrainerf.2bpp.lz"
R_CooltrainerMSpriteGFX::      INCBIN "gfx/overworld/rijon/r_cooltrainerm.2bpp.lz"
R_CueballSpriteGFX::           INCBIN "gfx/overworld/rijon/r_cueball.2bpp.lz"
R_EngineerSpriteGFX::          INCBIN "gfx/overworld/rijon/r_engineer.2bpp.lz"
R_GentlemanSpriteGFX::         INCBIN "gfx/overworld/rijon/r_gentleman.2bpp.lz"
R_FisherSpriteGFX::            INCBIN "gfx/overworld/rijon/r_fisher.2bpp.lz"
R_GamblerSpriteGFX::           INCBIN "gfx/overworld/rijon/r_gambler.2bpp.lz"

SECTION "Sprites small 1", ROMX, BANK[SPRITES_SMALL_1]

MinerSpriteGFX::        INCBIN "gfx/overworld/miner.2bpp.lz"
GuitaristFSpriteGFX::   INCBIN "gfx/overworld/guitaristF.2bpp.lz"
DelinquentFSpriteGFX::  INCBIN "gfx/overworld/delinquentF.2bpp.lz"
DelinquentMSpriteGFX::  INCBIN "gfx/overworld/delinquentM.2bpp.lz"
CheerleaderSpriteGFX::  INCBIN "gfx/overworld/cheerleader.2bpp.lz"

SECTION "Sprites small 2", ROMX, BANK[SPRITES_SMALL_2]

R_HikerSpriteGFX::             INCBIN "gfx/overworld/rijon/r_hiker.2bpp.lz"
R_JrTrainerFSpriteGFX::        INCBIN "gfx/overworld/rijon/r_jrtrainerf.2bpp.lz"
R_JrTrainerMSpriteGFX::        INCBIN "gfx/overworld/rijon/r_jrtrainerm.2bpp.lz"
R_JugglerSpriteGFX::           INCBIN "gfx/overworld/rijon/r_juggler.2bpp.lz"

SECTION "Sprites small 3", ROMX, BANK[SPRITES_SMALL_3]

R_LassSpriteGFX::              INCBIN "gfx/overworld/rijon/r_lass.2bpp.lz"
R_ManiacSpriteGFX::            INCBIN "gfx/overworld/rijon/r_maniac.2bpp.lz"
R_NerdSpriteGFX::              INCBIN "gfx/overworld/rijon/r_nerd.2bpp.lz"

SECTION "Sprites small 4", ROMX, BANK[SPRITES_SMALL_4]

MagikarpWalkGFX::              INCBIN "gfx/overworld/107.2bpp.lz"
FireSpriteGFX::                INCBIN "gfx/overworld/fire.2bpp.lz"

SECTION "Player Sprites 1", ROMX, BANK[PLAYER_SPRITES_1]

FishingGFX::
FishingGFXM1:: INCBIN "gfx/overworld/p0fish.2bpp"
FishingGFXF1:: INCBIN "gfx/overworld/p1fish.2bpp"
FishingGFXM2:: INCBIN "gfx/overworld/p2fish.2bpp"
FishingGFXF2:: INCBIN "gfx/overworld/p3fish.2bpp"
FishingGFXM3:: INCBIN "gfx/overworld/p4fish.2bpp"
FishingGFXF3:: INCBIN "gfx/overworld/p5fish.2bpp"
FishingGFXM4:: INCBIN "gfx/overworld/p6fish.2bpp"
FishingGFXF4:: INCBIN "gfx/overworld/p7fish.2bpp"
FishingGFXM5:: INCBIN "gfx/overworld/p8fish.2bpp"
FishingGFXF5:: INCBIN "gfx/overworld/p9fish.2bpp"
FishingGFXM6:: INCBIN "gfx/overworld/p10fish.2bpp"
FishingGFXF6:: INCBIN "gfx/overworld/p11fish.2bpp"
FishingGFXExtra:: INCBIN "gfx/overworld/fish_extra.2bpp"
FishingGFX7::  INCBIN "gfx/overworld/p12fish.2bpp"

FieldMoveSpriteGFX::
Player0FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p0field.2bpp"
Player1FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p1field.2bpp"
Player2FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p2field.2bpp"
Player3FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p3field.2bpp"
Player4FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p4field.2bpp"
Player5FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p5field.2bpp"
Player6FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p6field.2bpp"
Player7FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p7field.2bpp"
Player8FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p8field.2bpp"
Player9FieldMoveSpriteGFX::  INCBIN "gfx/overworld/p9field.2bpp"
Player10FieldMoveSpriteGFX:: INCBIN "gfx/overworld/p10field.2bpp"
Player11FieldMoveSpriteGFX:: INCBIN "gfx/overworld/p11field.2bpp"
Player12FieldMoveSpriteGFX:: INCBIN "gfx/overworld/p12field.2bpp"

SECTION "Player Sprites 2", ROMX, BANK[PLAYER_SPRITES_2]

Player0SurfSpriteGFX::  INCBIN "gfx/overworld/p0surf.2bpp.lz"
Player1SurfSpriteGFX::  INCBIN "gfx/overworld/p1surf.2bpp.lz"
Player2SpriteGFX::      INCBIN "gfx/overworld/p2.2bpp.lz"
Player2BikeSpriteGFX::  INCBIN "gfx/overworld/p2bike.2bpp.lz"
Player2SurfSpriteGFX::  INCBIN "gfx/overworld/p2surf.2bpp.lz"
Player3SpriteGFX::      INCBIN "gfx/overworld/p3.2bpp.lz"
Player3BikeSpriteGFX::  INCBIN "gfx/overworld/p3bike.2bpp.lz"
Player3SurfSpriteGFX::  INCBIN "gfx/overworld/p3surf.2bpp.lz"
Player4SpriteGFX::      INCBIN "gfx/overworld/p4.2bpp.lz"
Player4BikeSpriteGFX::  INCBIN "gfx/overworld/p4bike.2bpp.lz"
Player4SurfSpriteGFX::  INCBIN "gfx/overworld/p4surf.2bpp.lz"
Player5SpriteGFX::      INCBIN "gfx/overworld/p5.2bpp.lz"
Player5BikeSpriteGFX::  INCBIN "gfx/overworld/p5bike.2bpp.lz"
Player5SurfSpriteGFX::  INCBIN "gfx/overworld/p5surf.2bpp.lz"
Player6SpriteGFX::      INCBIN "gfx/overworld/p6.2bpp.lz"
Player6BikeSpriteGFX::  INCBIN "gfx/overworld/p6bike.2bpp.lz"
Player6SurfSpriteGFX::  INCBIN "gfx/overworld/p6surf.2bpp.lz"
Player7SpriteGFX::      INCBIN "gfx/overworld/p7.2bpp.lz"
Player7BikeSpriteGFX::  INCBIN "gfx/overworld/p7bike.2bpp.lz"
Player7SurfSpriteGFX::  INCBIN "gfx/overworld/p7surf.2bpp.lz"
Player8SpriteGFX::      INCBIN "gfx/overworld/p8.2bpp.lz"
Player8BikeSpriteGFX::  INCBIN "gfx/overworld/p8bike.2bpp.lz"
Player8SurfSpriteGFX::  INCBIN "gfx/overworld/p8surf.2bpp.lz"
Player9SpriteGFX::      INCBIN "gfx/overworld/p9.2bpp.lz"
Player9BikeSpriteGFX::  INCBIN "gfx/overworld/p9bike.2bpp.lz"
Player9SurfSpriteGFX::  INCBIN "gfx/overworld/p9surf.2bpp.lz"
Player10SpriteGFX::     INCBIN "gfx/overworld/p10.2bpp.lz"
Player10BikeSpriteGFX:: INCBIN "gfx/overworld/p10bike.2bpp.lz"
Player10SurfSpriteGFX:: INCBIN "gfx/overworld/p10surf.2bpp.lz"
Player11SpriteGFX::     INCBIN "gfx/overworld/p11.2bpp.lz"
Player11BikeSpriteGFX:: INCBIN "gfx/overworld/p11bike.2bpp.lz"
Player11SurfSpriteGFX:: INCBIN "gfx/overworld/p11surf.2bpp.lz"
Player12BikeSpriteGFX:: INCBIN "gfx/overworld/p12bike.2bpp.lz"
Player12SurfSpriteGFX:: INCBIN "gfx/overworld/p12surf.2bpp.lz"
