SECTION "Pic Pointers", ROMX[$4000], BANK[PIC_POINTERS]
PicPointers:: INCLUDE "gfx/pics/pic_pointers.asm"

SECTION "Trainer Pic Pointers", ROMX, BANK[TRAINER_PIC_POINTERS]
TrainerPicPointers:: INCLUDE "gfx/pics/trainer_pic_pointers.asm"

SECTION "Pics 1", ROMX, BANK[PICS_1]

AronBackPic:         INCBIN "gfx/pics/aron/back.2bpp.lz"
LaironBackPic:       INCBIN "gfx/pics/lairon/back.2bpp.lz"
AggronBackPic:       INCBIN "gfx/pics/aggron/back.2bpp.lz"
BronzongBackPic:     INCBIN "gfx/pics/bronzong/back.2bpp.lz"
CranidosBackPic:     INCBIN "gfx/pics/cranidos/back.2bpp.lz"
RampardosBackPic:    INCBIN "gfx/pics/rampardos/back.2bpp.lz"
ShieldonBackPic:     INCBIN "gfx/pics/shieldon/back.2bpp.lz"
BastiodonBackPic:    INCBIN "gfx/pics/bastiodon/back.2bpp.lz"
WhismurBackPic:      INCBIN "gfx/pics/whismur/back.2bpp.lz"
LoudredBackPic:      INCBIN "gfx/pics/loudred/back.2bpp.lz"
ExploudBackPic:      INCBIN "gfx/pics/exploud/back.2bpp.lz"
MagnezoneBackPic:    INCBIN "gfx/pics/magnezone/back.2bpp.lz"
DrifloonBackPic:     INCBIN "gfx/pics/drifloon/back.2bpp.lz"
DrifblimBackPic:     INCBIN "gfx/pics/drifblim/back.2bpp.lz"
SableyeBackPic:      INCBIN "gfx/pics/sableye/back.2bpp.lz"
ShuppetBackPic:      INCBIN "gfx/pics/shuppet/back.2bpp.lz"
BanetteBackPic:      INCBIN "gfx/pics/banette/back.2bpp.lz"
DuskullBackPic:      INCBIN "gfx/pics/duskull/back.2bpp.lz"
DusclopsBackPic:     INCBIN "gfx/pics/dusclops/back.2bpp.lz"
LunatoneBackPic:     INCBIN "gfx/pics/lunatone/back.2bpp.lz"
SolrockBackPic:      INCBIN "gfx/pics/solrock/back.2bpp.lz"
TrapinchBackPic:     INCBIN "gfx/pics/trapinch/back.2bpp.lz"
VibravaBackPic:      INCBIN "gfx/pics/vibrava/back.2bpp.lz"
FlygonBackPic:       INCBIN "gfx/pics/flygon/back.2bpp.lz"
CacneaBackPic:       INCBIN "gfx/pics/cacnea/back.2bpp.lz"
CacturneBackPic:     INCBIN "gfx/pics/cacturne/back.2bpp.lz"
MakuhitaBackPic:     INCBIN "gfx/pics/makuhita/back.2bpp.lz"
HariyamaBackPic:     INCBIN "gfx/pics/hariyama/back.2bpp.lz"
TangrowthBackPic:    INCBIN "gfx/pics/tangrowth/back.2bpp.lz"
ElectivireBackPic:   INCBIN "gfx/pics/electivire/back.2bpp.lz"
MagmortarBackPic:    INCBIN "gfx/pics/magmortar/back.2bpp.lz"
LotadBackPic:        INCBIN "gfx/pics/lotad/back.2bpp.lz"
LombreBackPic:       INCBIN "gfx/pics/lombre/back.2bpp.lz"
LudicoloBackPic:     INCBIN "gfx/pics/ludicolo/back.2bpp.lz"
RelicanthBackPic:    INCBIN "gfx/pics/relicanth/back.2bpp.lz"
MawileBackPic:       INCBIN "gfx/pics/mawile/back.2bpp.lz"
AbsolBackPic:        INCBIN "gfx/pics/absol/back.2bpp.lz"
LileepBackPic:       INCBIN "gfx/pics/lileep/back.2bpp.lz"
CradilyBackPic:      INCBIN "gfx/pics/cradily/back.2bpp.lz"
AnorithBackPic:      INCBIN "gfx/pics/anorith/back.2bpp.lz"
ArmaldoBackPic:      INCBIN "gfx/pics/armaldo/back.2bpp.lz"
BeldumBackPic:       INCBIN "gfx/pics/beldum/back.2bpp.lz"
MetangBackPic:       INCBIN "gfx/pics/metang/back.2bpp.lz"
MetagrossBackPic:    INCBIN "gfx/pics/metagross/back.2bpp.lz"
RaltsBackPic:        INCBIN "gfx/pics/ralts/back.2bpp.lz"
KirliaBackPic:       INCBIN "gfx/pics/kirlia/back.2bpp.lz"
GardevoirBackPic:    INCBIN "gfx/pics/gardevoir/back.2bpp.lz"
GalladeBackPic:      INCBIN "gfx/pics/gallade/back.2bpp.lz"
CarnivineBackPic:    INCBIN "gfx/pics/carnivine/back.2bpp.lz"
TogekissBackPic:     INCBIN "gfx/pics/togekiss/back.2bpp.lz"
NumelBackPic:        INCBIN "gfx/pics/numel/back.2bpp.lz"
CameruptBackPic:     INCBIN "gfx/pics/camerupt/back.2bpp.lz"
WailmerBackPic:      INCBIN "gfx/pics/wailmer/back.2bpp.lz"
WailordBackPic:      INCBIN "gfx/pics/wailord/back.2bpp.lz"
MasquerainBackPic:   INCBIN "gfx/pics/masquerain/back.2bpp.lz"
ShroomishBackPic:    INCBIN "gfx/pics/shroomish/back.2bpp.lz"
BreloomBackPic:      INCBIN "gfx/pics/breloom/back.2bpp.lz"

SECTION "Pics 2", ROMX, BANK[PICS_2]

RinjiPic:            INCBIN "gfx/trainers/rinji.2bpp.lz"
EdisonPic:           INCBIN "gfx/trainers/edison.2bpp.lz"
AndrePic:            INCBIN "gfx/trainers/andre.2bpp.lz"
KarpmanPic:          INCBIN "gfx/trainers/karpman.2bpp.lz"
LilyPic:             INCBIN "gfx/trainers/lily.2bpp.lz"
WailmerFrontPic:     INCBIN "gfx/pics/wailmer/front.2bpp.lz"
KyogreFrontPic:      INCBIN "gfx/pics/kyogre/front.2bpp.lz"
LibabeelFrontPic:    INCBIN "gfx/pics/libabeel/front.2bpp.lz"
GroudonFrontPic:     INCBIN "gfx/pics/groudon/front.2bpp.lz"
RaltsFrontPic:       INCBIN "gfx/pics/ralts/front.2bpp.lz"

SECTION "Pics 3", ROMX, BANK[PICS_3]

SurskitBackPic:      INCBIN "gfx/pics/surskit/back.2bpp.lz"
YanmegaBackPic:      INCBIN "gfx/pics/yanmega/back.2bpp.lz"
LeafeonBackPic:      INCBIN "gfx/pics/leafeon/back.2bpp.lz"
GlaceonBackPic:      INCBIN "gfx/pics/glaceon/back.2bpp.lz"
SylveonBackPic:      INCBIN "gfx/pics/sylveon/back.2bpp.lz"
MismagiusBackPic:    INCBIN "gfx/pics/mismagius/back.2bpp.lz"
SwabluBackPic:       INCBIN "gfx/pics/swablu/back.2bpp.lz"
AltariaBackPic:      INCBIN "gfx/pics/altaria/back.2bpp.lz"
RhyperiorBackPic:    INCBIN "gfx/pics/rhyperior/back.2bpp.lz"
GliscorBackPic:      INCBIN "gfx/pics/gliscor/back.2bpp.lz"
FeebasBackPic:       INCBIN "gfx/pics/feebas/back.2bpp.lz"
MiloticBackPic:      INCBIN "gfx/pics/milotic/back.2bpp.lz"
RioluBackPic:        INCBIN "gfx/pics/riolu/back.2bpp.lz"
LucarioBackPic:      INCBIN "gfx/pics/lucario/back.2bpp.lz"
GibleBackPic:        INCBIN "gfx/pics/gible/back.2bpp.lz"
GabiteBackPic:       INCBIN "gfx/pics/gabite/back.2bpp.lz"
GarchompBackPic:     INCBIN "gfx/pics/garchomp/back.2bpp.lz"
BagonBackPic:        INCBIN "gfx/pics/bagon/back.2bpp.lz"
ShelgonBackPic:      INCBIN "gfx/pics/shelgon/back.2bpp.lz"
SalamenceBackPic:    INCBIN "gfx/pics/salamence/back.2bpp.lz"
MamoswineBackPic:    INCBIN "gfx/pics/mamoswine/back.2bpp.lz"
PorygonzBackPic:     INCBIN "gfx/pics/porygonz/back.2bpp.lz"
WeavileBackPic:      INCBIN "gfx/pics/weavile/back.2bpp.lz"
GroudonBackPic:      INCBIN "gfx/pics/groudon/back.2bpp.lz"
KyogreBackPic:       INCBIN "gfx/pics/kyogre/back.2bpp.lz"
RayquazaBackPic:     INCBIN "gfx/pics/rayquaza/back.2bpp.lz"
PhanceroBackPic:     INCBIN "gfx/pics/phancero/back.2bpp.lz"

SECTION "Pics 4", ROMX, BANK[PICS_4]

RaiwatoFrontPic:     INCBIN "gfx/pics/raiwato/front.2bpp.lz"
RaiwatoBackPic:      INCBIN "gfx/pics/raiwato/back.2bpp.lz"
VaraneousFrontPic:   INCBIN "gfx/pics/varaneous/front.2bpp.lz"
VaraneousBackPic:    INCBIN "gfx/pics/varaneous/back.2bpp.lz"
LibabeelBackPic:     INCBIN "gfx/pics/libabeel/back.2bpp.lz"
DaichiPic:           INCBIN "gfx/trainers/daichi.2bpp.lz"
DelinquentFPic:      INCBIN "gfx/trainers/delinquentF.2bpp.lz"
SparkyPic:           INCBIN "gfx/trainers/sparky.2bpp.lz"
YukiPic:             INCBIN "gfx/trainers/yuki.2bpp.lz"

SECTION "Pics 5", ROMX, BANK[PICS_5]

HoOhFrontPic:        INCBIN "gfx/pics/hooh/front.2bpp.lz"
MachampFrontPic:     INCBIN "gfx/pics/machamp/front.2bpp.lz"
NinetalesFrontPic:   INCBIN "gfx/pics/ninetales/front.2bpp.lz"
FeraligatrFrontPic:  INCBIN "gfx/pics/feraligatr/front.2bpp.lz"
LugiaFrontPic:       INCBIN "gfx/pics/lugia/front.2bpp.lz"
ArticunoFrontPic:    INCBIN "gfx/pics/articuno/front.2bpp.lz"
VenusaurFrontPic:    INCBIN "gfx/pics/venusaur/front.2bpp.lz"
TyphlosionFrontPic:  INCBIN "gfx/pics/typhlosion/front.2bpp.lz"
BlastoiseFrontPic:   INCBIN "gfx/pics/blastoise/front.2bpp.lz"
RapidashFrontPic:    INCBIN "gfx/pics/rapidash/front.2bpp.lz"
MeganiumFrontPic:    INCBIN "gfx/pics/meganium/front.2bpp.lz"
HitmonleeFrontPic:   INCBIN "gfx/pics/hitmonlee/front.2bpp.lz"
ArcanineFrontPic:    INCBIN "gfx/pics/arcanine/front.2bpp.lz"
VenonatBackPic:      INCBIN "gfx/pics/venonat/back.2bpp.lz"

SECTION "Pics 6", ROMX, BANK[PICS_6]

TyranitarFrontPic:   INCBIN "gfx/pics/tyranitar/front.2bpp.lz"
MoltresFrontPic:     INCBIN "gfx/pics/moltres/front.2bpp.lz"
ZapdosFrontPic:      INCBIN "gfx/pics/zapdos/front.2bpp.lz"
MewtwoFrontPic:      INCBIN "gfx/pics/mewtwo/front.2bpp.lz"
FearowFrontPic:      INCBIN "gfx/pics/fearow/front.2bpp.lz"
CharizardFrontPic:   INCBIN "gfx/pics/charizard/front.2bpp.lz"
QuilavaFrontPic:     INCBIN "gfx/pics/quilava/front.2bpp.lz"
SteelixFrontPic:     INCBIN "gfx/pics/steelix/front.2bpp.lz"
AlakazamFrontPic:    INCBIN "gfx/pics/alakazam/front.2bpp.lz"
GyaradosFrontPic:    INCBIN "gfx/pics/gyarados/front.2bpp.lz"
KangaskhanFrontPic:  INCBIN "gfx/pics/kangaskhan/front.2bpp.lz"
RhydonFrontPic:      INCBIN "gfx/pics/rhydon/front.2bpp.lz"
RhyhornFrontPic:     INCBIN "gfx/pics/rhyhorn/front.2bpp.lz"
PidgeotFrontPic:     INCBIN "gfx/pics/pidgeot/front.2bpp.lz"
SlowbroFrontPic:     INCBIN "gfx/pics/slowbro/front.2bpp.lz"
ButterfreeFrontPic:  INCBIN "gfx/pics/butterfree/front.2bpp.lz"
WeezingFrontPic:     INCBIN "gfx/pics/weezing/front.2bpp.lz"
SurskitFrontPic:     INCBIN "gfx/pics/surskit/front.2bpp.lz"

SECTION "Pics 7", ROMX, BANK[PICS_7]

VictreebelFrontPic:  INCBIN "gfx/pics/victreebel/front.2bpp.lz"
VictreebelBackPic:   INCBIN "gfx/pics/victreebel/back.2bpp.lz"
SlowkingFrontPic:    INCBIN "gfx/pics/slowking/front.2bpp.lz"
HitmontopFrontPic:   INCBIN "gfx/pics/hitmontop/front.2bpp.lz"
OnixFrontPic:        INCBIN "gfx/pics/onix/front.2bpp.lz"
BlisseyFrontPic:     INCBIN "gfx/pics/blissey/front.2bpp.lz"
MachokeFrontPic:     INCBIN "gfx/pics/machoke/front.2bpp.lz"
ScytherFrontPic:     INCBIN "gfx/pics/scyther/front.2bpp.lz"
SeakingFrontPic:     INCBIN "gfx/pics/seaking/front.2bpp.lz"
CroconawFrontPic:    INCBIN "gfx/pics/croconaw/front.2bpp.lz"
JolteonFrontPic:     INCBIN "gfx/pics/jolteon/front.2bpp.lz"
DonphanFrontPic:     INCBIN "gfx/pics/donphan/front.2bpp.lz"
GolbatFrontPic:      INCBIN "gfx/pics/golbat/front.2bpp.lz"
ExeggcuteFrontPic:   INCBIN "gfx/pics/exeggcute/front.2bpp.lz"
TogepiBackPic:       INCBIN "gfx/pics/togepi/back.2bpp.lz"
CrobatBackPic:       INCBIN "gfx/pics/crobat/back.2bpp.lz"
FearowBackPic:       INCBIN "gfx/pics/fearow/back.2bpp.lz"
MarillBackPic:       INCBIN "gfx/pics/marill/back.2bpp.lz"
MetapodBackPic:      INCBIN "gfx/pics/metapod/back.2bpp.lz"
DittoBackPic:        INCBIN "gfx/pics/ditto/back.2bpp.lz"
MagcargoFrontPic:    INCBIN "gfx/pics/magcargo/front.2bpp.lz"
VenomothFrontPic:    INCBIN "gfx/pics/venomoth/front.2bpp.lz"
ElectabuzzFrontPic:  INCBIN "gfx/pics/electabuzz/front.2bpp.lz"
CharmeleonFrontPic:  INCBIN "gfx/pics/charmeleon/front.2bpp.lz"
TyrogueFrontPic:     INCBIN "gfx/pics/tyrogue/front.2bpp.lz"

SECTION "Pics 8", ROMX, BANK[PICS_8]

KadabraFrontPic:     INCBIN "gfx/pics/kadabra/front.2bpp.lz"
ExeggutorFrontPic:   INCBIN "gfx/pics/exeggutor/front.2bpp.lz"
GastlyFrontPic:      INCBIN "gfx/pics/gastly/front.2bpp.lz"
AzumarillFrontPic:   INCBIN "gfx/pics/azumarill/front.2bpp.lz"
ParasectFrontPic:    INCBIN "gfx/pics/parasect/front.2bpp.lz"
AriadosFrontPic:     INCBIN "gfx/pics/ariados/front.2bpp.lz"
WartortleFrontPic:   INCBIN "gfx/pics/wartortle/front.2bpp.lz"
GolemFrontPic:       INCBIN "gfx/pics/golem/front.2bpp.lz"
UrsaringFrontPic:    INCBIN "gfx/pics/ursaring/front.2bpp.lz"
HoundoomFrontPic:    INCBIN "gfx/pics/houndoom/front.2bpp.lz"
AmpharosFrontPic:    INCBIN "gfx/pics/ampharos/front.2bpp.lz"
FlareonFrontPic:     INCBIN "gfx/pics/flareon/front.2bpp.lz"
BayleefFrontPic:     INCBIN "gfx/pics/bayleef/front.2bpp.lz"
MagmarFrontPic:      INCBIN "gfx/pics/magmar/front.2bpp.lz"
TentacruelFrontPic:  INCBIN "gfx/pics/tentacruel/front.2bpp.lz"
AmpharosBackPic:     INCBIN "gfx/pics/ampharos/back.2bpp.lz"
BlisseyBackPic:      INCBIN "gfx/pics/blissey/back.2bpp.lz"
IgglybuffBackPic:    INCBIN "gfx/pics/igglybuff/back.2bpp.lz"
AzumarillBackPic:    INCBIN "gfx/pics/azumarill/back.2bpp.lz"
SentretBackPic:      INCBIN "gfx/pics/sentret/back.2bpp.lz"
ElekidFrontPic:      INCBIN "gfx/pics/elekid/front.2bpp.lz"
VulpixFrontPic:      INCBIN "gfx/pics/vulpix/front.2bpp.lz"
VaporeonFrontPic:    INCBIN "gfx/pics/vaporeon/front.2bpp.lz"
SneaselFrontPic:     INCBIN "gfx/pics/sneasel/front.2bpp.lz"
VenonatFrontPic:     INCBIN "gfx/pics/venonat/front.2bpp.lz"
VenusaurBackPic:     INCBIN "gfx/pics/venusaur/back.2bpp.lz"
TrapinchFrontPic:    INCBIN "gfx/pics/trapinch/front.2bpp.lz"

SECTION "Pics 9", ROMX, BANK[PICS_9]

IllumiseBackPic:     INCBIN "gfx/pics/illumise/back.2bpp.lz"
BronzorBackPic:      INCBIN "gfx/pics/bronzor/back.2bpp.lz"
VaporeonBackPic:     INCBIN "gfx/pics/vaporeon/back.2bpp.lz"
SnorlaxFrontPic:     INCBIN "gfx/pics/snorlax/front.2bpp.lz"
WigglytuffFrontPic:  INCBIN "gfx/pics/wigglytuff/front.2bpp.lz"
YanmaFrontPic:       INCBIN "gfx/pics/yanma/front.2bpp.lz"
PonytaFrontPic:      INCBIN "gfx/pics/ponyta/front.2bpp.lz"
PidgeottoFrontPic:   INCBIN "gfx/pics/pidgeotto/front.2bpp.lz"
GengarFrontPic:      INCBIN "gfx/pics/gengar/front.2bpp.lz"
PiloswineFrontPic:   INCBIN "gfx/pics/piloswine/front.2bpp.lz"
MagnetonFrontPic:    INCBIN "gfx/pics/magneton/front.2bpp.lz"
ForretressFrontPic:  INCBIN "gfx/pics/forretress/front.2bpp.lz"
TogeticFrontPic:     INCBIN "gfx/pics/togetic/front.2bpp.lz"
KangaskhanBackPic:   INCBIN "gfx/pics/kangaskhan/back.2bpp.lz"
CrobatFrontPic:      INCBIN "gfx/pics/crobat/front.2bpp.lz"
ChanseyFrontPic:     INCBIN "gfx/pics/chansey/front.2bpp.lz"
TangelaFrontPic:     INCBIN "gfx/pics/tangela/front.2bpp.lz"
HaunterFrontPic:     INCBIN "gfx/pics/haunter/front.2bpp.lz"
UmbreonFrontPic:     INCBIN "gfx/pics/umbreon/front.2bpp.lz"
ChikoritaFrontPic:   INCBIN "gfx/pics/chikorita/front.2bpp.lz"
JigglypuffBackPic:   INCBIN "gfx/pics/jigglypuff/back.2bpp.lz"
SpinarakBackPic:     INCBIN "gfx/pics/spinarak/back.2bpp.lz"
HoundourBackPic:     INCBIN "gfx/pics/houndour/back.2bpp.lz"
SquirtleBackPic:     INCBIN "gfx/pics/squirtle/back.2bpp.lz"
SlowpokeBackPic:     INCBIN "gfx/pics/slowpoke/back.2bpp.lz"
GoldeenFrontPic:     INCBIN "gfx/pics/goldeen/front.2bpp.lz"
EspeonFrontPic:      INCBIN "gfx/pics/espeon/front.2bpp.lz"
XatuFrontPic:        INCBIN "gfx/pics/xatu/front.2bpp.lz"
MewFrontPic:         INCBIN "gfx/pics/mew/front.2bpp.lz"
LopunnyFrontPic:     INCBIN "gfx/pics/lopunny/front.2bpp.lz"

SECTION "Pics 10", ROMX, BANK[PICS_10]

GravelerFrontPic:    INCBIN "gfx/pics/graveler/front.2bpp.lz"
FlaaffyFrontPic:     INCBIN "gfx/pics/flaaffy/front.2bpp.lz"
IvysaurFrontPic:     INCBIN "gfx/pics/ivysaur/front.2bpp.lz"
FurretFrontPic:      INCBIN "gfx/pics/furret/front.2bpp.lz"
CyndaquilFrontPic:   INCBIN "gfx/pics/cyndaquil/front.2bpp.lz"
HitmonchanFrontPic:  INCBIN "gfx/pics/hitmonchan/front.2bpp.lz"
PikachuFrontPic:     INCBIN "gfx/pics/pikachu/front.2bpp.lz"
MagbyFrontPic:       INCBIN "gfx/pics/magby/front.2bpp.lz"
WeepinbellFrontPic:  INCBIN "gfx/pics/weepinbell/front.2bpp.lz"
TotodileFrontPic:    INCBIN "gfx/pics/totodile/front.2bpp.lz"
FirebreatherPic:     INCBIN "gfx/trainers/firebreather.2bpp.lz"
MachopFrontPic:      INCBIN "gfx/pics/machop/front.2bpp.lz"
ChinchouFrontPic:    INCBIN "gfx/pics/chinchou/front.2bpp.lz"
SpearowFrontPic:     INCBIN "gfx/pics/spearow/front.2bpp.lz"
MagikarpFrontPic:    INCBIN "gfx/pics/magikarp/front.2bpp.lz"
BlackbeltTPic:       INCBIN "gfx/trainers/blackbelt_t.2bpp.lz"
BikerPic:            INCBIN "gfx/trainers/biker.2bpp.lz"
PorygonFrontPic:     INCBIN "gfx/pics/porygon/front.2bpp.lz"
BrunoPic:            INCBIN "gfx/trainers/bruno.2bpp.lz"
HikerPic:            INCBIN "gfx/trainers/hiker.2bpp.lz"
Porygon2FrontPic:    INCBIN "gfx/pics/porygon2/front.2bpp.lz"
PidgeyFrontPic:      INCBIN "gfx/pics/pidgey/front.2bpp.lz"
ParasectBackPic:     INCBIN "gfx/pics/parasect/back.2bpp.lz"
HoundourFrontPic:    INCBIN "gfx/pics/houndour/front.2bpp.lz"
MediumPic:           INCBIN "gfx/trainers/medium.2bpp.lz"
PinecoFrontPic:      INCBIN "gfx/pics/pineco/front.2bpp.lz"
FisherPic:           INCBIN "gfx/trainers/fisher.2bpp.lz"
JigglypuffFrontPic:  INCBIN "gfx/pics/jigglypuff/front.2bpp.lz"
ParasFrontPic:       INCBIN "gfx/pics/paras/front.2bpp.lz"
CharmanderFrontPic:  INCBIN "gfx/pics/charmander/front.2bpp.lz"
ChampionPic:         INCBIN "gfx/trainers/champion.2bpp.lz"

SECTION "Pics 11", ROMX, BANK[PICS_11]

BoarderPic:          INCBIN "gfx/trainers/boarder.2bpp.lz"
SquirtleFrontPic:    INCBIN "gfx/pics/squirtle/front.2bpp.lz"
MachampBackPic:      INCBIN "gfx/pics/machamp/back.2bpp.lz"
KoffingFrontPic:     INCBIN "gfx/pics/koffing/front.2bpp.lz"
ExeggutorBackPic:    INCBIN "gfx/pics/exeggutor/back.2bpp.lz"
LanturnFrontPic:     INCBIN "gfx/pics/lanturn/front.2bpp.lz"
MareepFrontPic:      INCBIN "gfx/pics/mareep/front.2bpp.lz"
EeveeFrontPic:       INCBIN "gfx/pics/eevee/front.2bpp.lz"
ButterfreeBackPic:   INCBIN "gfx/pics/butterfree/back.2bpp.lz"
ZubatFrontPic:       INCBIN "gfx/pics/zubat/front.2bpp.lz"
KimonoGirlPic:       INCBIN "gfx/trainers/kimono_girl.2bpp.lz"
AlakazamBackPic:     INCBIN "gfx/pics/alakazam/back.2bpp.lz"
AbraFrontPic:        INCBIN "gfx/pics/abra/front.2bpp.lz"
HitmontopBackPic:    INCBIN "gfx/pics/hitmontop/back.2bpp.lz"
SlugmaFrontPic:      INCBIN "gfx/pics/slugma/front.2bpp.lz"
GrowlitheFrontPic:   INCBIN "gfx/pics/growlithe/front.2bpp.lz"
SlowpokeFrontPic:    INCBIN "gfx/pics/slowpoke/front.2bpp.lz"
JugglerPic:          INCBIN "gfx/trainers/juggler.2bpp.lz"
MarillFrontPic:      INCBIN "gfx/pics/marill/front.2bpp.lz"
GuitaristPic:        INCBIN "gfx/trainers/guitarist.2bpp.lz"
PokefanfPic:         INCBIN "gfx/trainers/pokefan_f.2bpp.lz"
VenomothBackPic:     INCBIN "gfx/pics/venomoth/back.2bpp.lz"
PokemaniacPic:       INCBIN "gfx/trainers/pokemaniac.2bpp.lz"
SkierPic:            INCBIN "gfx/trainers/skier.2bpp.lz"
PupitarFrontPic:     INCBIN "gfx/pics/pupitar/front.2bpp.lz"
BellsproutFrontPic:  INCBIN "gfx/pics/bellsprout/front.2bpp.lz"
TentacoolFrontPic:   INCBIN "gfx/pics/tentacool/front.2bpp.lz"
GyaradosBackPic:     INCBIN "gfx/pics/gyarados/back.2bpp.lz"
NinetalesBackPic:    INCBIN "gfx/pics/ninetales/back.2bpp.lz"
YanmaBackPic:        INCBIN "gfx/pics/yanma/back.2bpp.lz"
LassPic:             INCBIN "gfx/trainers/lass.2bpp.lz"
FeraligatrBackPic:   INCBIN "gfx/pics/feraligatr/back.2bpp.lz"
MagnetonBackPic:     INCBIN "gfx/pics/magneton/back.2bpp.lz"
SlowkingBackPic:     INCBIN "gfx/pics/slowking/back.2bpp.lz"
BulbasaurBackPic:    INCBIN "gfx/pics/bulbasaur/back.2bpp.lz"
AronFrontPic:        INCBIN "gfx/pics/aron/front.2bpp.lz"
AyakaPic:            INCBIN "gfx/trainers/ayaka.2bpp.lz"
CheerleaderPic:      INCBIN "gfx/trainers/cheerleader.2bpp.lz"

SECTION "Pics 12", ROMX, BANK[PICS_12]

ElekidBackPic:       INCBIN "gfx/pics/elekid/back.2bpp.lz"
BugCatcherPic:       INCBIN "gfx/trainers/bug_catcher.2bpp.lz"
SnorlaxBackPic:      INCBIN "gfx/pics/snorlax/back.2bpp.lz"
MoltresBackPic:      INCBIN "gfx/pics/moltres/back.2bpp.lz"
PhanpyFrontPic:      INCBIN "gfx/pics/phanpy/front.2bpp.lz"
RhydonBackPic:       INCBIN "gfx/pics/rhydon/back.2bpp.lz"
LarvitarFrontPic:    INCBIN "gfx/pics/larvitar/front.2bpp.lz"
TyranitarBackPic:    INCBIN "gfx/pics/tyranitar/back.2bpp.lz"
TwinsPic:            INCBIN "gfx/trainers/twins.2bpp.lz"
CyndaquilBackPic:    INCBIN "gfx/pics/cyndaquil/back.2bpp.lz"
BayleefBackPic:      INCBIN "gfx/pics/bayleef/back.2bpp.lz"
RapidashBackPic:     INCBIN "gfx/pics/rapidash/back.2bpp.lz"
MagmarBackPic:       INCBIN "gfx/pics/magmar/back.2bpp.lz"
QuilavaBackPic:      INCBIN "gfx/pics/quilava/back.2bpp.lz"
CroconawBackPic:     INCBIN "gfx/pics/croconaw/back.2bpp.lz"
SailorPic:           INCBIN "gfx/trainers/sailor.2bpp.lz"
BeautyPic:           INCBIN "gfx/trainers/beauty.2bpp.lz"
ZubatBackPic:        INCBIN "gfx/pics/zubat/back.2bpp.lz"
TeddiursaFrontPic:   INCBIN "gfx/pics/teddiursa/front.2bpp.lz"
MagcargoBackPic:     INCBIN "gfx/pics/magcargo/back.2bpp.lz"
ArcanineBackPic:     INCBIN "gfx/pics/arcanine/back.2bpp.lz"
FlareonBackPic:      INCBIN "gfx/pics/flareon/back.2bpp.lz"
GoldeenBackPic:      INCBIN "gfx/pics/goldeen/back.2bpp.lz"
BulbasaurFrontPic:   INCBIN "gfx/pics/bulbasaur/front.2bpp.lz"
PidgeyBackPic:       INCBIN "gfx/pics/pidgey/back.2bpp.lz"
ScientistPic:        INCBIN "gfx/trainers/scientist.2bpp.lz"
PiloswineBackPic:    INCBIN "gfx/pics/piloswine/back.2bpp.lz"
NatuBackPic:         INCBIN "gfx/pics/natu/back.2bpp.lz"
GolemBackPic:        INCBIN "gfx/pics/golem/back.2bpp.lz"
GolbatBackPic:       INCBIN "gfx/pics/golbat/back.2bpp.lz"
ForretressBackPic:   INCBIN "gfx/pics/forretress/back.2bpp.lz"
GligarBackPic:       INCBIN "gfx/pics/gligar/back.2bpp.lz"
TyphlosionBackPic:   INCBIN "gfx/pics/typhlosion/back.2bpp.lz"
CharmeleonBackPic:   INCBIN "gfx/pics/charmeleon/back.2bpp.lz"
PichuFrontPic:       INCBIN "gfx/pics/pichu/front.2bpp.lz"
ElectabuzzBackPic:   INCBIN "gfx/pics/electabuzz/back.2bpp.lz"
PupitarBackPic:      INCBIN "gfx/pics/pupitar/back.2bpp.lz"
SteelixBackPic:      INCBIN "gfx/pics/steelix/back.2bpp.lz"
TeacherPic:          INCBIN "gfx/trainers/teacher.2bpp.lz"
EggFrontPic:
EggBackPic:
EggPic:              INCBIN "gfx/pics/egg/front.2bpp.lz"
CacturneFrontPic:    INCBIN "gfx/pics/cacturne/front.2bpp.lz"
MuraPic:             INCBIN "gfx/trainers/mura.2bpp.lz"

SECTION "Pics 13", ROMX, BANK[PICS_13]

EeveeBackPic:        INCBIN "gfx/pics/eevee/back.2bpp.lz"
PonytaBackPic:       INCBIN "gfx/pics/ponyta/back.2bpp.lz"
OnixBackPic:         INCBIN "gfx/pics/onix/back.2bpp.lz"
KoffingBackPic:      INCBIN "gfx/pics/koffing/back.2bpp.lz"
BirdKeeperPic:       INCBIN "gfx/trainers/bird_keeper.2bpp.lz"
TentacruelBackPic:   INCBIN "gfx/pics/tentacruel/back.2bpp.lz"
GrowlitheBackPic:    INCBIN "gfx/pics/growlithe/back.2bpp.lz"
MachokeBackPic:      INCBIN "gfx/pics/machoke/back.2bpp.lz"
RaichuBackPic:       INCBIN "gfx/pics/raichu/back.2bpp.lz"
SwimmermPic:         INCBIN "gfx/trainers/swimmer_m.2bpp.lz"
MysticalmanPic:      INCBIN "gfx/trainers/mysticalman.2bpp.lz"
CooltrainerfPic:     INCBIN "gfx/trainers/cooltrainer_f.2bpp.lz"
FlaaffyBackPic:      INCBIN "gfx/pics/flaaffy/back.2bpp.lz"
SentretFrontPic:     INCBIN "gfx/pics/sentret/front.2bpp.lz"
TogeticBackPic:      INCBIN "gfx/pics/togetic/back.2bpp.lz"
GeodudeBackPic:      INCBIN "gfx/pics/geodude/back.2bpp.lz"
ScytherBackPic:      INCBIN "gfx/pics/scyther/back.2bpp.lz"
HitmonchanBackPic:   INCBIN "gfx/pics/hitmonchan/back.2bpp.lz"
CooltrainermPic:     INCBIN "gfx/trainers/cooltrainer_m.2bpp.lz"
BlastoiseBackPic:    INCBIN "gfx/pics/blastoise/back.2bpp.lz"
MisdreavusBackPic:   INCBIN "gfx/pics/misdreavus/back.2bpp.lz"
TyrogueBackPic:      INCBIN "gfx/pics/tyrogue/back.2bpp.lz"
GeodudeFrontPic:     INCBIN "gfx/pics/geodude/front.2bpp.lz"
ScizorBackPic:       INCBIN "gfx/pics/scizor/back.2bpp.lz"
CharizardBackPic:    INCBIN "gfx/pics/charizard/back.2bpp.lz"
KadabraBackPic:      INCBIN "gfx/pics/kadabra/back.2bpp.lz"
FurretBackPic:       INCBIN "gfx/pics/furret/back.2bpp.lz"
WartortleBackPic:    INCBIN "gfx/pics/wartortle/back.2bpp.lz"
DonphanBackPic:      INCBIN "gfx/pics/donphan/back.2bpp.lz"
WigglytuffBackPic:   INCBIN "gfx/pics/wigglytuff/back.2bpp.lz"
TangelaBackPic:      INCBIN "gfx/pics/tangela/back.2bpp.lz"
GastlyBackPic:       INCBIN "gfx/pics/gastly/back.2bpp.lz"
ExeggcuteBackPic:    INCBIN "gfx/pics/exeggcute/back.2bpp.lz"
IgglybuffFrontPic:   INCBIN "gfx/pics/igglybuff/front.2bpp.lz"
SeakingBackPic:      INCBIN "gfx/pics/seaking/back.2bpp.lz"
BurglarPic:          INCBIN "gfx/trainers/burglar.2bpp.lz"
PikachuBackPic:      INCBIN "gfx/pics/pikachu/back.2bpp.lz"
VulpixBackPic:       INCBIN "gfx/pics/vulpix/back.2bpp.lz"
MareepBackPic:       INCBIN "gfx/pics/mareep/back.2bpp.lz"
DittoFrontPic:       INCBIN "gfx/pics/ditto/front.2bpp.lz"
CamperPic:           INCBIN "gfx/trainers/camper.2bpp.lz"
UmbreonBackPic:      INCBIN "gfx/pics/umbreon/back.2bpp.lz"
PidgeotBackPic:      INCBIN "gfx/pics/pidgeot/back.2bpp.lz"
BugsyPic:            INCBIN "gfx/trainers/bugsy.2bpp.lz"
CadencePic:          INCBIN "gfx/trainers/cadence.2bpp.lz"
MinerPic:            INCBIN "gfx/trainers/miner.2bpp.lz"

SECTION "Pics 14", ROMX, BANK[PICS_14]

Rival1Pic:           INCBIN "gfx/trainers/rival1.2bpp.lz"
SwinubBackPic:       INCBIN "gfx/pics/swinub/back.2bpp.lz"
MewtwoBackPic:       INCBIN "gfx/pics/mewtwo/back.2bpp.lz"
CalPic:              INCBIN "gfx/trainers/cal.2bpp.lz"
SwimmerfPic:         INCBIN "gfx/trainers/swimmer_f.2bpp.lz"
OfficerPic:          INCBIN "gfx/trainers/officer.2bpp.lz"
MagikarpBackPic:     INCBIN "gfx/pics/magikarp/back.2bpp.lz"
SneaselBackPic:      INCBIN "gfx/pics/sneasel/back.2bpp.lz"
IvysaurBackPic:      INCBIN "gfx/pics/ivysaur/back.2bpp.lz"
SlowbroBackPic:      INCBIN "gfx/pics/slowbro/back.2bpp.lz"
PsychicTPic:         INCBIN "gfx/trainers/psychic_t.2bpp.lz"
WeezingBackPic:      INCBIN "gfx/pics/weezing/back.2bpp.lz"
HoOhBackPic:         INCBIN "gfx/pics/hooh/back.2bpp.lz"
MewBackPic:          INCBIN "gfx/pics/mew/back.2bpp.lz"
MachopBackPic:       INCBIN "gfx/pics/machop/back.2bpp.lz"
AbraBackPic:         INCBIN "gfx/pics/abra/back.2bpp.lz"
WeepinbellBackPic:   INCBIN "gfx/pics/weepinbell/back.2bpp.lz"
GravelerBackPic:     INCBIN "gfx/pics/graveler/back.2bpp.lz"
EspeonBackPic:       INCBIN "gfx/pics/espeon/back.2bpp.lz"
TotodileBackPic:     INCBIN "gfx/pics/totodile/back.2bpp.lz"
GengarBackPic:       INCBIN "gfx/pics/gengar/back.2bpp.lz"
YoungsterPic:        INCBIN "gfx/trainers/youngster.2bpp.lz"
SchoolboyPic:        INCBIN "gfx/trainers/schoolboy.2bpp.lz"
MagnemiteFrontPic:   INCBIN "gfx/pics/magnemite/front.2bpp.lz"
MagnemiteBackPic:    INCBIN "gfx/pics/magnemite/back.2bpp.lz"
SlugmaBackPic:       INCBIN "gfx/pics/slugma/back.2bpp.lz"
MeganiumBackPic:     INCBIN "gfx/pics/meganium/back.2bpp.lz"
PicnickerPic:        INCBIN "gfx/trainers/picnicker.2bpp.lz"
TogepiFrontPic:      INCBIN "gfx/pics/togepi/front.2bpp.lz"
SuperNerdPic:        INCBIN "gfx/trainers/super_nerd.2bpp.lz"
HaunterBackPic:      INCBIN "gfx/pics/haunter/back.2bpp.lz"
XatuBackPic:         INCBIN "gfx/pics/xatu/back.2bpp.lz"
Porygon2BackPic:     INCBIN "gfx/pics/porygon2/back.2bpp.lz"
PinecoBackPic:       INCBIN "gfx/pics/pineco/back.2bpp.lz"
MetapodFrontPic:     INCBIN "gfx/pics/metapod/front.2bpp.lz"
JolteonBackPic:      INCBIN "gfx/pics/jolteon/back.2bpp.lz"
CaterpieFrontPic:    INCBIN "gfx/pics/caterpie/front.2bpp.lz"
GentlemanPic:        INCBIN "gfx/trainers/gentleman.2bpp.lz"
SpearowBackPic:      INCBIN "gfx/pics/spearow/back.2bpp.lz"
MagbyBackPic:        INCBIN "gfx/pics/magby/back.2bpp.lz"
BluePic:             INCBIN "gfx/trainers/blue.2bpp.lz"
RedPic:              INCBIN "gfx/trainers/red.2bpp.lz"
WhitneyPic:          INCBIN "gfx/trainers/whitney.2bpp.lz"
SabrinaPic:          INCBIN "gfx/trainers/sabrina.2bpp.lz"
KojiPic:             INCBIN "gfx/trainers/koji.2bpp.lz"
DelinquentMPic:      INCBIN "gfx/trainers/delinquentM.2bpp.lz"
TrainerKrisPic:      INCBIN "gfx/trainers/trainerkris.2bpp.lz"
JosiahPic:           INCBIN "gfx/trainers/josiah.2bpp.lz"
GuitaristFPic:       INCBIN "gfx/trainers/guitaristF.2bpp.lz"

SECTION "Pics 15", ROMX, BANK[PICS_15]

ArticunoBackPic:     INCBIN "gfx/pics/articuno/back.2bpp.lz"
ZapdosBackPic:       INCBIN "gfx/pics/zapdos/back.2bpp.lz"
ChikoritaBackPic:    INCBIN "gfx/pics/chikorita/back.2bpp.lz"
ChinchouBackPic:     INCBIN "gfx/pics/chinchou/back.2bpp.lz"
ChanseyBackPic:      INCBIN "gfx/pics/chansey/back.2bpp.lz"
SpinarakFrontPic:    INCBIN "gfx/pics/spinarak/front.2bpp.lz"
CharmanderBackPic:   INCBIN "gfx/pics/charmander/back.2bpp.lz"
RhyhornBackPic:      INCBIN "gfx/pics/rhyhorn/back.2bpp.lz"
SwinubFrontPic:      INCBIN "gfx/pics/swinub/front.2bpp.lz"
LarvitarBackPic:     INCBIN "gfx/pics/larvitar/back.2bpp.lz"
PorygonBackPic:      INCBIN "gfx/pics/porygon/back.2bpp.lz"
ParasBackPic:        INCBIN "gfx/pics/paras/back.2bpp.lz"
TentacoolBackPic:    INCBIN "gfx/pics/tentacool/back.2bpp.lz"
PichuBackPic:        INCBIN "gfx/pics/pichu/back.2bpp.lz"
HoundoomBackPic:     INCBIN "gfx/pics/houndoom/back.2bpp.lz"
BellsproutBackPic:   INCBIN "gfx/pics/bellsprout/back.2bpp.lz"
LanturnBackPic:      INCBIN "gfx/pics/lanturn/back.2bpp.lz"
PidgeottoBackPic:    INCBIN "gfx/pics/pidgeotto/back.2bpp.lz"
CaterpieBackPic:     INCBIN "gfx/pics/caterpie/back.2bpp.lz"
LugiaBackPic:        INCBIN "gfx/pics/lugia/back.2bpp.lz"
HitmonleeBackPic:    INCBIN "gfx/pics/hitmonlee/back.2bpp.lz"
NatuFrontPic:        INCBIN "gfx/pics/natu/front.2bpp.lz"
UrsaringBackPic:     INCBIN "gfx/pics/ursaring/back.2bpp.lz"
SagePic:             INCBIN "gfx/trainers/sage.2bpp.lz"
TeddiursaBackPic:    INCBIN "gfx/pics/teddiursa/back.2bpp.lz"
ArcadePCPic:         INCBIN "gfx/trainers/arcadepc.2bpp.lz"
ScizorFrontPic:      INCBIN "gfx/pics/scizor/front.2bpp.lz"
PhanpyBackPic:       INCBIN "gfx/pics/phanpy/back.2bpp.lz"
ChinglingFrontPic:   INCBIN "gfx/pics/chingling/front.2bpp.lz"
ChimechoFrontPic:    INCBIN "gfx/pics/chimecho/front.2bpp.lz"
TorkoalFrontPic:     INCBIN "gfx/pics/torkoal/front.2bpp.lz"
TaillowFrontPic:     INCBIN "gfx/pics/taillow/front.2bpp.lz"
BunearyFrontPic:     INCBIN "gfx/pics/buneary/front.2bpp.lz"
AltariaFrontPic:     INCBIN "gfx/pics/altaria/front.2bpp.lz"
BrownPic:            INCBIN "gfx/trainers/brown.2bpp.lz"
Rival2Pic:           INCBIN "gfx/trainers/rival2.2bpp.lz"
LoisPic:             INCBIN "gfx/trainers/lois.2bpp.lz"
JoePic:              INCBIN "gfx/trainers/joe.2bpp.lz"
BrucePic:            INCBIN "gfx/trainers/bruce.2bpp.lz"

SECTION "Pics 16", ROMX, BANK[PICS_16]

ShinxFrontPic:       INCBIN "gfx/pics/shinx/front.2bpp.lz"
LuxioFrontPic:       INCBIN "gfx/pics/luxio/front.2bpp.lz"
LuxrayFrontPic:      INCBIN "gfx/pics/luxray/front.2bpp.lz"
ElectrikeFrontPic:   INCBIN "gfx/pics/electrike/front.2bpp.lz"
ManectricFrontPic:   INCBIN "gfx/pics/manectric/front.2bpp.lz"
SnoruntFrontPic:     INCBIN "gfx/pics/snorunt/front.2bpp.lz"
GlalieFrontPic:      INCBIN "gfx/pics/glalie/front.2bpp.lz"
FroslassFrontPic:    INCBIN "gfx/pics/froslass/front.2bpp.lz"
VolbeatFrontPic:     INCBIN "gfx/pics/volbeat/front.2bpp.lz"
IllumiseFrontPic:    INCBIN "gfx/pics/illumise/front.2bpp.lz"
RayquazaFrontPic:    INCBIN "gfx/pics/rayquaza/front.2bpp.lz"
LaironFrontPic:      INCBIN "gfx/pics/lairon/front.2bpp.lz"
AggronFrontPic:      INCBIN "gfx/pics/aggron/front.2bpp.lz"
BronzorFrontPic:     INCBIN "gfx/pics/bronzor/front.2bpp.lz"
BronzongFrontPic:    INCBIN "gfx/pics/bronzong/front.2bpp.lz"
SkorupiFrontPic:     INCBIN "gfx/pics/skorupi/front.2bpp.lz"
DrapionFrontPic:     INCBIN "gfx/pics/drapion/front.2bpp.lz"
SpiritombFrontPic:   INCBIN "gfx/pics/spiritomb/front.2bpp.lz"
AriadosBackPic:      INCBIN "gfx/pics/ariados/back.2bpp.lz"

SECTION "Pics 17", ROMX, BANK[PICS_17]

CranidosFrontPic:    INCBIN "gfx/pics/cranidos/front.2bpp.lz"
RampardosFrontPic:   INCBIN "gfx/pics/rampardos/front.2bpp.lz"
ShieldonFrontPic:    INCBIN "gfx/pics/shieldon/front.2bpp.lz"
BastiodonFrontPic:   INCBIN "gfx/pics/bastiodon/front.2bpp.lz"
WhismurFrontPic:     INCBIN "gfx/pics/whismur/front.2bpp.lz"
ExploudFrontPic:     INCBIN "gfx/pics/exploud/front.2bpp.lz"
DrifloonFrontPic:    INCBIN "gfx/pics/drifloon/front.2bpp.lz"
DrifblimFrontPic:    INCBIN "gfx/pics/drifblim/front.2bpp.lz"
SableyeFrontPic:     INCBIN "gfx/pics/sableye/front.2bpp.lz"
ShuppetFrontPic:     INCBIN "gfx/pics/shuppet/front.2bpp.lz"
BanetteFrontPic:     INCBIN "gfx/pics/banette/front.2bpp.lz"
DuskullFrontPic:     INCBIN "gfx/pics/duskull/front.2bpp.lz"
DusclopsFrontPic:    INCBIN "gfx/pics/dusclops/front.2bpp.lz"
LunatoneFrontPic:    INCBIN "gfx/pics/lunatone/front.2bpp.lz"
SolrockFrontPic:     INCBIN "gfx/pics/solrock/front.2bpp.lz"
GarchompFrontPic:    INCBIN "gfx/pics/garchomp/front.2bpp.lz"
LoudredFrontPic:     INCBIN "gfx/pics/loudred/front.2bpp.lz"

SECTION "Pics 18", ROMX, BANK[PICS_18]

MagnezoneFrontPic:   INCBIN "gfx/pics/magnezone/front.2bpp.lz"
VibravaFrontPic:     INCBIN "gfx/pics/vibrava/front.2bpp.lz"
FlygonFrontPic:      INCBIN "gfx/pics/flygon/front.2bpp.lz"
MakuhitaFrontPic:    INCBIN "gfx/pics/makuhita/front.2bpp.lz"
HariyamaFrontPic:    INCBIN "gfx/pics/hariyama/front.2bpp.lz"
CacneaFrontPic:      INCBIN "gfx/pics/cacnea/front.2bpp.lz"
TangrowthFrontPic:   INCBIN "gfx/pics/tangrowth/front.2bpp.lz"
LombreFrontPic:      INCBIN "gfx/pics/lombre/front.2bpp.lz"
LudicoloFrontPic:    INCBIN "gfx/pics/ludicolo/front.2bpp.lz"
RelicanthFrontPic:   INCBIN "gfx/pics/relicanth/front.2bpp.lz"
ElectivireFrontPic:  INCBIN "gfx/pics/electivire/front.2bpp.lz"
MagmortarFrontPic:   INCBIN "gfx/pics/magmortar/front.2bpp.lz"
AbsolFrontPic:       INCBIN "gfx/pics/absol/front.2bpp.lz"
RaichuFrontPic:      INCBIN "gfx/pics/raichu/front.2bpp.lz"
LileepFrontPic:      INCBIN "gfx/pics/lileep/front.2bpp.lz"
AnorithFrontPic:     INCBIN "gfx/pics/anorith/front.2bpp.lz"
BeldumFrontPic:      INCBIN "gfx/pics/beldum/front.2bpp.lz"

SECTION "Pics 19", ROMX, BANK[PICS_19]

CradilyFrontPic:     INCBIN "gfx/pics/cradily/front.2bpp.lz"
MetangFrontPic:      INCBIN "gfx/pics/metang/front.2bpp.lz"
MetagrossFrontPic:   INCBIN "gfx/pics/metagross/front.2bpp.lz"
KirliaFrontPic:      INCBIN "gfx/pics/kirlia/front.2bpp.lz"
GalladeFrontPic:     INCBIN "gfx/pics/gallade/front.2bpp.lz"
GardevoirFrontPic:   INCBIN "gfx/pics/gardevoir/front.2bpp.lz"
CarnivineFrontPic:   INCBIN "gfx/pics/carnivine/front.2bpp.lz"
NumelFrontPic:       INCBIN "gfx/pics/numel/front.2bpp.lz"
CameruptFrontPic:    INCBIN "gfx/pics/camerupt/front.2bpp.lz"
MasquerainFrontPic:  INCBIN "gfx/pics/masquerain/front.2bpp.lz"
ShroomishFrontPic:   INCBIN "gfx/pics/shroomish/front.2bpp.lz"
BreloomFrontPic:     INCBIN "gfx/pics/breloom/front.2bpp.lz"
YanmegaFrontPic:     INCBIN "gfx/pics/yanmega/front.2bpp.lz"
FambacoFrontPic:     INCBIN "gfx/pics/fambaco/front.2bpp.lz"
LotadFrontPic:       INCBIN "gfx/pics/lotad/front.2bpp.lz"
ErnestPic:           INCBIN "gfx/trainers/ernest.2bpp.lz"
SpiritombBackPic:    INCBIN "gfx/pics/spiritomb/back.2bpp.lz"
SkorupiBackPic:      INCBIN "gfx/pics/skorupi/back.2bpp.lz"

SECTION "Pics 20", ROMX, BANK[PICS_20]

MismagiusFrontPic:   INCBIN "gfx/pics/mismagius/front.2bpp.lz"
SwabluFrontPic:      INCBIN "gfx/pics/swablu/front.2bpp.lz"
RhyperiorFrontPic:   INCBIN "gfx/pics/rhyperior/front.2bpp.lz"
GliscorFrontPic:     INCBIN "gfx/pics/gliscor/front.2bpp.lz"
FeebasFrontPic:      INCBIN "gfx/pics/feebas/front.2bpp.lz"
RioluFrontPic:       INCBIN "gfx/pics/riolu/front.2bpp.lz"
LucarioFrontPic:     INCBIN "gfx/pics/lucario/front.2bpp.lz"
GabiteFrontPic:      INCBIN "gfx/pics/gabite/front.2bpp.lz"
ShelgonFrontPic:     INCBIN "gfx/pics/shelgon/front.2bpp.lz"
SalamenceFrontPic:   INCBIN "gfx/pics/salamence/front.2bpp.lz"
MamoswineFrontPic:   INCBIN "gfx/pics/mamoswine/front.2bpp.lz"
PorygonzFrontPic:    INCBIN "gfx/pics/porygonz/front.2bpp.lz"
WeavileFrontPic:     INCBIN "gfx/pics/weavile/front.2bpp.lz"
PhanceroFrontPic:    INCBIN "gfx/pics/phancero/front.2bpp.lz"

SECTION "Pics 21", ROMX, BANK[PICS_21]

WailordFrontPic:     INCBIN "gfx/pics/wailord/front.2bpp.lz"
LeafeonFrontPic:     INCBIN "gfx/pics/leafeon/front.2bpp.lz"
GlaceonFrontPic:     INCBIN "gfx/pics/glaceon/front.2bpp.lz"
SylveonFrontPic:     INCBIN "gfx/pics/sylveon/front.2bpp.lz"
TogekissFrontPic:    INCBIN "gfx/pics/togekiss/front.2bpp.lz"
GibleFrontPic:       INCBIN "gfx/pics/gible/front.2bpp.lz"
BagonFrontPic:       INCBIN "gfx/pics/bagon/front.2bpp.lz"
SwellowFrontPic:     INCBIN "gfx/pics/swellow/front.2bpp.lz"
ArmaldoFrontPic:     INCBIN "gfx/pics/armaldo/front.2bpp.lz"
MiloticFrontPic:     INCBIN "gfx/pics/milotic/front.2bpp.lz"
MawileFrontPic:      INCBIN "gfx/pics/mawile/front.2bpp.lz"
MisdreavusFrontPic:  INCBIN "gfx/pics/misdreavus/front.2bpp.lz"
CandelaPic:          INCBIN "gfx/trainers/candela.2bpp.lz"
BlanchePic:          INCBIN "gfx/trainers/blanche.2bpp.lz"
SparkPic:            INCBIN "gfx/trainers/spark.2bpp.lz"
ChimechoBackPic:     INCBIN "gfx/pics/chimecho/back.2bpp.lz"
TorkoalBackPic:      INCBIN "gfx/pics/torkoal/back.2bpp.lz"
TaillowBackPic:      INCBIN "gfx/pics/taillow/back.2bpp.lz"
SwellowBackPic:      INCBIN "gfx/pics/swellow/back.2bpp.lz"
BunearyBackPic:      INCBIN "gfx/pics/buneary/back.2bpp.lz"
LopunnyBackPic:      INCBIN "gfx/pics/lopunny/back.2bpp.lz"
ElectrikeBackPic:    INCBIN "gfx/pics/electrike/back.2bpp.lz"
ManectricBackPic:    INCBIN "gfx/pics/manectric/back.2bpp.lz"
SnoruntBackPic:      INCBIN "gfx/pics/snorunt/back.2bpp.lz"
GlalieBackPic:       INCBIN "gfx/pics/glalie/back.2bpp.lz"
FroslassBackPic:     INCBIN "gfx/pics/froslass/back.2bpp.lz"
GoldPic:             INCBIN "gfx/trainers/gold.2bpp.lz"

PlayerPalettePatroller::     INCBIN "gfx/trainers/chris.7x7_6.2bpp"
PlayerPalettePatrollerBack:: INCBIN "gfx/backpics/pp.6x6.2bpp"

SECTION "Pics small 1", ROMX, BANK[PICS_SMALL_1]

ShinxBackPic:        INCBIN "gfx/pics/shinx/back.2bpp.lz"
LuxioBackPic:        INCBIN "gfx/pics/luxio/back.2bpp.lz"
LuxrayBackPic:       INCBIN "gfx/pics/luxray/back.2bpp.lz"
DrapionBackPic:      INCBIN "gfx/pics/drapion/back.2bpp.lz"

SECTION "Pics small 2", ROMX, BANK[PICS_SMALL_2]

VolbeatBackPic:      INCBIN "gfx/pics/volbeat/back.2bpp.lz"
GligarFrontPic:      INCBIN "gfx/pics/gligar/front.2bpp.lz"

SECTION "Pics small 3", ROMX, BANK[PICS_SMALL_3]

GruntmPic:           INCBIN "gfx/trainers/grunt_m.2bpp.lz"

SECTION "Pics small 4", ROMX, BANK[PICS_SMALL_4]

SherylPic:           INCBIN "gfx/trainers/sheryl.2bpp.lz"
GiovanniPic:         INCBIN "gfx/trainers/giovanni.2bpp.lz"
SoraPic:             INCBIN "gfx/trainers/sora.2bpp.lz"
BrooklynPic:         INCBIN "gfx/trainers/brooklyn.2bpp.lz"

SECTION "Pics small 5", ROMX, BANK[PICS_SMALL_5]

PokefanmPic:         INCBIN "gfx/trainers/pokefan_m.2bpp.lz"

SECTION "Pics small 6", ROMX, BANK[PICS_SMALL_6]

FambacoBackPic:      INCBIN "gfx/pics/fambaco/back.2bpp.lz"

SECTION "Pics small 7", ROMX, BANK[PICS_SMALL_7]

ChinglingBackPic:    INCBIN "gfx/pics/chingling/back.2bpp.lz"

SECTION "Player Pics", ROMX[$4000], BANK[PLAYER_PICS]

PlayerPics::
ChrisPic:  INCBIN "gfx/trainers/chris.7x7_0.2bpp"
KrisPic:   INCBIN "gfx/trainers/kris.7x7_0.2bpp"
ChrisPic2: INCBIN "gfx/trainers/chris.7x7_1.2bpp"
KrisPic2:  INCBIN "gfx/trainers/kris.7x7_1.2bpp"
ChrisPic3: INCBIN "gfx/trainers/chris.7x7_2.2bpp"
KrisPic3:  INCBIN "gfx/trainers/kris.7x7_2.2bpp"
ChrisPic4: INCBIN "gfx/trainers/chris.7x7_3.2bpp"
KrisPic4:  INCBIN "gfx/trainers/kris.7x7_3.2bpp"
ChrisPic5: INCBIN "gfx/trainers/chris.7x7_4.2bpp"
KrisPic5:  INCBIN "gfx/trainers/kris.7x7_4.2bpp"
ChrisPic6: INCBIN "gfx/trainers/chris.7x7_5.2bpp"
KrisPic6:  INCBIN "gfx/trainers/kris.7x7_5.2bpp"

PlayerBackpics::
ChrisBackpic:  INCBIN "gfx/backpics/p0.6x6.2bpp"
KrisBackpic:   INCBIN "gfx/backpics/p1.6x6.2bpp"
ChrisBackpic2: INCBIN "gfx/backpics/p2.6x6.2bpp"
KrisBackpic2:  INCBIN "gfx/backpics/p3.6x6.2bpp"
ChrisBackpic3: INCBIN "gfx/backpics/p4.6x6.2bpp"
KrisBackpic3:  INCBIN "gfx/backpics/p5.6x6.2bpp"
ChrisBackpic4: INCBIN "gfx/backpics/p6.6x6.2bpp"
KrisBackpic4:  INCBIN "gfx/backpics/p7.6x6.2bpp"
ChrisBackpic5: INCBIN "gfx/backpics/p8.6x6.2bpp"
KrisBackpic5:  INCBIN "gfx/backpics/p9.6x6.2bpp"
ChrisBackpic6: INCBIN "gfx/backpics/p10.6x6.2bpp"
KrisBackpic6:  INCBIN "gfx/backpics/p11.6x6.2bpp"
