	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "Rival"
	add_name "Elite Four"
	add_name "Elite Four"
	add_name "Leader"
	add_name "Elite Four"
	add_name "Delinquent"
	add_name "Elite Four"
	add_name "Champion"
	add_name "Palette"
	add_name "Scientist"
	add_name "Youngster"
	add_name "Schoolboy"
	add_name "Bird Keeper"
	add_name "Lass"
	add_name "Cheerleader"
	add_name "Cooltrainer"
	add_name "Cooltrainer"
	add_name "Beauty"
	add_name "#maniac"
	add_name "Rocket"
	add_name "Gentleman"
	add_name "Skier"
	add_name "Teacher"
	add_name "Leader"
	add_name "Bug Catcher"
	add_name "Fisher"
	add_name "Swimmer"
	add_name "Swimmer"
	add_name "Sailor"
	add_name "Super Nerd"
	add_name "Silver"
	add_name "Guitarist"
	add_name "Hiker"
	add_name "Biker"
	add_name "Leader"
	add_name "Burglar"
	add_name "Firebreather"
	add_name "Juggler"
	add_name "Blackbelt"
	add_name "Psychic"
	add_name "Picnicker"
	add_name "Camper"
	add_name "Sage"
	add_name "Medium"
	add_name "Boarder"
	add_name "#fan"
	add_name "Delinquent"
	add_name "Twins"
	add_name "#fan"
	add_name "<PKMN> Trainer"
	add_name "<PKMN> Trainer"
	add_name "Officer"
	add_name "Miner"
	add_name "Leader"
	add_name "Battle"
	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "<PKMN> Trainer"
	add_name "Leader"
	add_name "Leader"
	add_name "<PKMN> Trainer"
	add_name "Kimono Girl"
	add_name "Leader"
	add_name "Leader"
	add_name "Leader"
	add_name "Tower Head"
	add_name "Tower Head"
	add_name "Tower Head"
	add_name "<PKMN> Trainer"
	add_name "Guitarist"
	add_name "<PKMN> Trainer"
